
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Employees` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Employees
 * 
 */
export type EmployeesModel = runtime.Types.Result.DefaultSelection<Prisma.$EmployeesPayload>

export type AggregateEmployees = {
  _count: EmployeesCountAggregateOutputType | null
  _min: EmployeesMinAggregateOutputType | null
  _max: EmployeesMaxAggregateOutputType | null
}

export type EmployeesMinAggregateOutputType = {
  id: string | null
  tenant_id: string | null
  email: string | null
  password_hash: string | null
  google_id: string | null
  name: string | null
  avatar_url: string | null
  is_active: boolean | null
  is_manager: boolean | null
  deactivated_at: Date | null
  invited_by_id: string | null
  invite_accepted_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type EmployeesMaxAggregateOutputType = {
  id: string | null
  tenant_id: string | null
  email: string | null
  password_hash: string | null
  google_id: string | null
  name: string | null
  avatar_url: string | null
  is_active: boolean | null
  is_manager: boolean | null
  deactivated_at: Date | null
  invited_by_id: string | null
  invite_accepted_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type EmployeesCountAggregateOutputType = {
  id: number
  tenant_id: number
  email: number
  password_hash: number
  google_id: number
  name: number
  avatar_url: number
  is_active: number
  is_manager: number
  deactivated_at: number
  invited_by_id: number
  invite_accepted_at: number
  created_at: number
  updated_at: number
  _all: number
}


export type EmployeesMinAggregateInputType = {
  id?: true
  tenant_id?: true
  email?: true
  password_hash?: true
  google_id?: true
  name?: true
  avatar_url?: true
  is_active?: true
  is_manager?: true
  deactivated_at?: true
  invited_by_id?: true
  invite_accepted_at?: true
  created_at?: true
  updated_at?: true
}

export type EmployeesMaxAggregateInputType = {
  id?: true
  tenant_id?: true
  email?: true
  password_hash?: true
  google_id?: true
  name?: true
  avatar_url?: true
  is_active?: true
  is_manager?: true
  deactivated_at?: true
  invited_by_id?: true
  invite_accepted_at?: true
  created_at?: true
  updated_at?: true
}

export type EmployeesCountAggregateInputType = {
  id?: true
  tenant_id?: true
  email?: true
  password_hash?: true
  google_id?: true
  name?: true
  avatar_url?: true
  is_active?: true
  is_manager?: true
  deactivated_at?: true
  invited_by_id?: true
  invite_accepted_at?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type EmployeesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Employees to aggregate.
   */
  where?: Prisma.EmployeesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employees to fetch.
   */
  orderBy?: Prisma.EmployeesOrderByWithRelationInput | Prisma.EmployeesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmployeesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Employees
  **/
  _count?: true | EmployeesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmployeesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmployeesMaxAggregateInputType
}

export type GetEmployeesAggregateType<T extends EmployeesAggregateArgs> = {
      [P in keyof T & keyof AggregateEmployees]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmployees[P]>
    : Prisma.GetScalarType<T[P], AggregateEmployees[P]>
}




export type EmployeesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmployeesWhereInput
  orderBy?: Prisma.EmployeesOrderByWithAggregationInput | Prisma.EmployeesOrderByWithAggregationInput[]
  by: Prisma.EmployeesScalarFieldEnum[] | Prisma.EmployeesScalarFieldEnum
  having?: Prisma.EmployeesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmployeesCountAggregateInputType | true
  _min?: EmployeesMinAggregateInputType
  _max?: EmployeesMaxAggregateInputType
}

export type EmployeesGroupByOutputType = {
  id: string
  tenant_id: string
  email: string
  password_hash: string | null
  google_id: string | null
  name: string
  avatar_url: string | null
  is_active: boolean
  is_manager: boolean
  deactivated_at: Date | null
  invited_by_id: string | null
  invite_accepted_at: Date | null
  created_at: Date
  updated_at: Date
  _count: EmployeesCountAggregateOutputType | null
  _min: EmployeesMinAggregateOutputType | null
  _max: EmployeesMaxAggregateOutputType | null
}

export type GetEmployeesGroupByPayload<T extends EmployeesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmployeesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmployeesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmployeesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmployeesGroupByOutputType[P]>
      }
    >
  >



export type EmployeesWhereInput = {
  AND?: Prisma.EmployeesWhereInput | Prisma.EmployeesWhereInput[]
  OR?: Prisma.EmployeesWhereInput[]
  NOT?: Prisma.EmployeesWhereInput | Prisma.EmployeesWhereInput[]
  id?: Prisma.StringFilter<"Employees"> | string
  tenant_id?: Prisma.StringFilter<"Employees"> | string
  email?: Prisma.StringFilter<"Employees"> | string
  password_hash?: Prisma.StringNullableFilter<"Employees"> | string | null
  google_id?: Prisma.StringNullableFilter<"Employees"> | string | null
  name?: Prisma.StringFilter<"Employees"> | string
  avatar_url?: Prisma.StringNullableFilter<"Employees"> | string | null
  is_active?: Prisma.BoolFilter<"Employees"> | boolean
  is_manager?: Prisma.BoolFilter<"Employees"> | boolean
  deactivated_at?: Prisma.DateTimeNullableFilter<"Employees"> | Date | string | null
  invited_by_id?: Prisma.StringNullableFilter<"Employees"> | string | null
  invite_accepted_at?: Prisma.DateTimeNullableFilter<"Employees"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Employees"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Employees"> | Date | string
  tenant?: Prisma.XOR<Prisma.TenantsScalarRelationFilter, Prisma.TenantsWhereInput>
  invited_by?: Prisma.XOR<Prisma.EmployeesNullableScalarRelationFilter, Prisma.EmployeesWhereInput> | null
  invited_users?: Prisma.EmployeesListRelationFilter
  tenants?: Prisma.TenantsListRelationFilter
}

export type EmployeesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrderInput | Prisma.SortOrder
  google_id?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_manager?: Prisma.SortOrder
  deactivated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  invited_by_id?: Prisma.SortOrderInput | Prisma.SortOrder
  invite_accepted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  tenant?: Prisma.TenantsOrderByWithRelationInput
  invited_by?: Prisma.EmployeesOrderByWithRelationInput
  invited_users?: Prisma.EmployeesOrderByRelationAggregateInput
  tenants?: Prisma.TenantsOrderByRelationAggregateInput
}

export type EmployeesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EmployeesWhereInput | Prisma.EmployeesWhereInput[]
  OR?: Prisma.EmployeesWhereInput[]
  NOT?: Prisma.EmployeesWhereInput | Prisma.EmployeesWhereInput[]
  tenant_id?: Prisma.StringFilter<"Employees"> | string
  email?: Prisma.StringFilter<"Employees"> | string
  password_hash?: Prisma.StringNullableFilter<"Employees"> | string | null
  google_id?: Prisma.StringNullableFilter<"Employees"> | string | null
  name?: Prisma.StringFilter<"Employees"> | string
  avatar_url?: Prisma.StringNullableFilter<"Employees"> | string | null
  is_active?: Prisma.BoolFilter<"Employees"> | boolean
  is_manager?: Prisma.BoolFilter<"Employees"> | boolean
  deactivated_at?: Prisma.DateTimeNullableFilter<"Employees"> | Date | string | null
  invited_by_id?: Prisma.StringNullableFilter<"Employees"> | string | null
  invite_accepted_at?: Prisma.DateTimeNullableFilter<"Employees"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Employees"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Employees"> | Date | string
  tenant?: Prisma.XOR<Prisma.TenantsScalarRelationFilter, Prisma.TenantsWhereInput>
  invited_by?: Prisma.XOR<Prisma.EmployeesNullableScalarRelationFilter, Prisma.EmployeesWhereInput> | null
  invited_users?: Prisma.EmployeesListRelationFilter
  tenants?: Prisma.TenantsListRelationFilter
}, "id">

export type EmployeesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrderInput | Prisma.SortOrder
  google_id?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrderInput | Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_manager?: Prisma.SortOrder
  deactivated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  invited_by_id?: Prisma.SortOrderInput | Prisma.SortOrder
  invite_accepted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.EmployeesCountOrderByAggregateInput
  _max?: Prisma.EmployeesMaxOrderByAggregateInput
  _min?: Prisma.EmployeesMinOrderByAggregateInput
}

export type EmployeesScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmployeesScalarWhereWithAggregatesInput | Prisma.EmployeesScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmployeesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmployeesScalarWhereWithAggregatesInput | Prisma.EmployeesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Employees"> | string
  tenant_id?: Prisma.StringWithAggregatesFilter<"Employees"> | string
  email?: Prisma.StringWithAggregatesFilter<"Employees"> | string
  password_hash?: Prisma.StringNullableWithAggregatesFilter<"Employees"> | string | null
  google_id?: Prisma.StringNullableWithAggregatesFilter<"Employees"> | string | null
  name?: Prisma.StringWithAggregatesFilter<"Employees"> | string
  avatar_url?: Prisma.StringNullableWithAggregatesFilter<"Employees"> | string | null
  is_active?: Prisma.BoolWithAggregatesFilter<"Employees"> | boolean
  is_manager?: Prisma.BoolWithAggregatesFilter<"Employees"> | boolean
  deactivated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"Employees"> | Date | string | null
  invited_by_id?: Prisma.StringNullableWithAggregatesFilter<"Employees"> | string | null
  invite_accepted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"Employees"> | Date | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Employees"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Employees"> | Date | string
}

export type EmployeesCreateInput = {
  id?: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  tenant: Prisma.TenantsCreateNestedOneWithoutEmployeesInput
  invited_by?: Prisma.EmployeesCreateNestedOneWithoutInvited_usersInput
  invited_users?: Prisma.EmployeesCreateNestedManyWithoutInvited_byInput
  tenants?: Prisma.TenantsCreateNestedManyWithoutManagerInput
}

export type EmployeesUncheckedCreateInput = {
  id?: string
  tenant_id: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invited_by_id?: string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  invited_users?: Prisma.EmployeesUncheckedCreateNestedManyWithoutInvited_byInput
  tenants?: Prisma.TenantsUncheckedCreateNestedManyWithoutManagerInput
}

export type EmployeesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.TenantsUpdateOneRequiredWithoutEmployeesNestedInput
  invited_by?: Prisma.EmployeesUpdateOneWithoutInvited_usersNestedInput
  invited_users?: Prisma.EmployeesUpdateManyWithoutInvited_byNestedInput
  tenants?: Prisma.TenantsUpdateManyWithoutManagerNestedInput
}

export type EmployeesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invited_by_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invited_users?: Prisma.EmployeesUncheckedUpdateManyWithoutInvited_byNestedInput
  tenants?: Prisma.TenantsUncheckedUpdateManyWithoutManagerNestedInput
}

export type EmployeesCreateManyInput = {
  id?: string
  tenant_id: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invited_by_id?: string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type EmployeesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invited_by_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeesNullableScalarRelationFilter = {
  is?: Prisma.EmployeesWhereInput | null
  isNot?: Prisma.EmployeesWhereInput | null
}

export type EmployeesListRelationFilter = {
  every?: Prisma.EmployeesWhereInput
  some?: Prisma.EmployeesWhereInput
  none?: Prisma.EmployeesWhereInput
}

export type EmployeesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmployeesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  google_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_manager?: Prisma.SortOrder
  deactivated_at?: Prisma.SortOrder
  invited_by_id?: Prisma.SortOrder
  invite_accepted_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type EmployeesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  google_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_manager?: Prisma.SortOrder
  deactivated_at?: Prisma.SortOrder
  invited_by_id?: Prisma.SortOrder
  invite_accepted_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type EmployeesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  google_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  avatar_url?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  is_manager?: Prisma.SortOrder
  deactivated_at?: Prisma.SortOrder
  invited_by_id?: Prisma.SortOrder
  invite_accepted_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type EmployeesCreateNestedOneWithoutInvited_usersInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_usersInput, Prisma.EmployeesUncheckedCreateWithoutInvited_usersInput>
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutInvited_usersInput
  connect?: Prisma.EmployeesWhereUniqueInput
}

export type EmployeesCreateNestedManyWithoutInvited_byInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_byInput, Prisma.EmployeesUncheckedCreateWithoutInvited_byInput> | Prisma.EmployeesCreateWithoutInvited_byInput[] | Prisma.EmployeesUncheckedCreateWithoutInvited_byInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutInvited_byInput | Prisma.EmployeesCreateOrConnectWithoutInvited_byInput[]
  createMany?: Prisma.EmployeesCreateManyInvited_byInputEnvelope
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
}

export type EmployeesUncheckedCreateNestedManyWithoutInvited_byInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_byInput, Prisma.EmployeesUncheckedCreateWithoutInvited_byInput> | Prisma.EmployeesCreateWithoutInvited_byInput[] | Prisma.EmployeesUncheckedCreateWithoutInvited_byInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutInvited_byInput | Prisma.EmployeesCreateOrConnectWithoutInvited_byInput[]
  createMany?: Prisma.EmployeesCreateManyInvited_byInputEnvelope
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EmployeesUpdateOneWithoutInvited_usersNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_usersInput, Prisma.EmployeesUncheckedCreateWithoutInvited_usersInput>
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutInvited_usersInput
  upsert?: Prisma.EmployeesUpsertWithoutInvited_usersInput
  disconnect?: Prisma.EmployeesWhereInput | boolean
  delete?: Prisma.EmployeesWhereInput | boolean
  connect?: Prisma.EmployeesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmployeesUpdateToOneWithWhereWithoutInvited_usersInput, Prisma.EmployeesUpdateWithoutInvited_usersInput>, Prisma.EmployeesUncheckedUpdateWithoutInvited_usersInput>
}

export type EmployeesUpdateManyWithoutInvited_byNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_byInput, Prisma.EmployeesUncheckedCreateWithoutInvited_byInput> | Prisma.EmployeesCreateWithoutInvited_byInput[] | Prisma.EmployeesUncheckedCreateWithoutInvited_byInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutInvited_byInput | Prisma.EmployeesCreateOrConnectWithoutInvited_byInput[]
  upsert?: Prisma.EmployeesUpsertWithWhereUniqueWithoutInvited_byInput | Prisma.EmployeesUpsertWithWhereUniqueWithoutInvited_byInput[]
  createMany?: Prisma.EmployeesCreateManyInvited_byInputEnvelope
  set?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  disconnect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  delete?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  update?: Prisma.EmployeesUpdateWithWhereUniqueWithoutInvited_byInput | Prisma.EmployeesUpdateWithWhereUniqueWithoutInvited_byInput[]
  updateMany?: Prisma.EmployeesUpdateManyWithWhereWithoutInvited_byInput | Prisma.EmployeesUpdateManyWithWhereWithoutInvited_byInput[]
  deleteMany?: Prisma.EmployeesScalarWhereInput | Prisma.EmployeesScalarWhereInput[]
}

export type EmployeesUncheckedUpdateManyWithoutInvited_byNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_byInput, Prisma.EmployeesUncheckedCreateWithoutInvited_byInput> | Prisma.EmployeesCreateWithoutInvited_byInput[] | Prisma.EmployeesUncheckedCreateWithoutInvited_byInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutInvited_byInput | Prisma.EmployeesCreateOrConnectWithoutInvited_byInput[]
  upsert?: Prisma.EmployeesUpsertWithWhereUniqueWithoutInvited_byInput | Prisma.EmployeesUpsertWithWhereUniqueWithoutInvited_byInput[]
  createMany?: Prisma.EmployeesCreateManyInvited_byInputEnvelope
  set?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  disconnect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  delete?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  update?: Prisma.EmployeesUpdateWithWhereUniqueWithoutInvited_byInput | Prisma.EmployeesUpdateWithWhereUniqueWithoutInvited_byInput[]
  updateMany?: Prisma.EmployeesUpdateManyWithWhereWithoutInvited_byInput | Prisma.EmployeesUpdateManyWithWhereWithoutInvited_byInput[]
  deleteMany?: Prisma.EmployeesScalarWhereInput | Prisma.EmployeesScalarWhereInput[]
}

export type EmployeesCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantInput, Prisma.EmployeesUncheckedCreateWithoutTenantInput> | Prisma.EmployeesCreateWithoutTenantInput[] | Prisma.EmployeesUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutTenantInput | Prisma.EmployeesCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.EmployeesCreateManyTenantInputEnvelope
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
}

export type EmployeesCreateNestedOneWithoutTenantsInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantsInput, Prisma.EmployeesUncheckedCreateWithoutTenantsInput>
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutTenantsInput
  connect?: Prisma.EmployeesWhereUniqueInput
}

export type EmployeesUncheckedCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantInput, Prisma.EmployeesUncheckedCreateWithoutTenantInput> | Prisma.EmployeesCreateWithoutTenantInput[] | Prisma.EmployeesUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutTenantInput | Prisma.EmployeesCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.EmployeesCreateManyTenantInputEnvelope
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
}

export type EmployeesUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantInput, Prisma.EmployeesUncheckedCreateWithoutTenantInput> | Prisma.EmployeesCreateWithoutTenantInput[] | Prisma.EmployeesUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutTenantInput | Prisma.EmployeesCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.EmployeesUpsertWithWhereUniqueWithoutTenantInput | Prisma.EmployeesUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.EmployeesCreateManyTenantInputEnvelope
  set?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  disconnect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  delete?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  update?: Prisma.EmployeesUpdateWithWhereUniqueWithoutTenantInput | Prisma.EmployeesUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.EmployeesUpdateManyWithWhereWithoutTenantInput | Prisma.EmployeesUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.EmployeesScalarWhereInput | Prisma.EmployeesScalarWhereInput[]
}

export type EmployeesUpdateOneWithoutTenantsNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantsInput, Prisma.EmployeesUncheckedCreateWithoutTenantsInput>
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutTenantsInput
  upsert?: Prisma.EmployeesUpsertWithoutTenantsInput
  disconnect?: Prisma.EmployeesWhereInput | boolean
  delete?: Prisma.EmployeesWhereInput | boolean
  connect?: Prisma.EmployeesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmployeesUpdateToOneWithWhereWithoutTenantsInput, Prisma.EmployeesUpdateWithoutTenantsInput>, Prisma.EmployeesUncheckedUpdateWithoutTenantsInput>
}

export type EmployeesUncheckedUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantInput, Prisma.EmployeesUncheckedCreateWithoutTenantInput> | Prisma.EmployeesCreateWithoutTenantInput[] | Prisma.EmployeesUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.EmployeesCreateOrConnectWithoutTenantInput | Prisma.EmployeesCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.EmployeesUpsertWithWhereUniqueWithoutTenantInput | Prisma.EmployeesUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.EmployeesCreateManyTenantInputEnvelope
  set?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  disconnect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  delete?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  connect?: Prisma.EmployeesWhereUniqueInput | Prisma.EmployeesWhereUniqueInput[]
  update?: Prisma.EmployeesUpdateWithWhereUniqueWithoutTenantInput | Prisma.EmployeesUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.EmployeesUpdateManyWithWhereWithoutTenantInput | Prisma.EmployeesUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.EmployeesScalarWhereInput | Prisma.EmployeesScalarWhereInput[]
}

export type EmployeesCreateWithoutInvited_usersInput = {
  id?: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  tenant: Prisma.TenantsCreateNestedOneWithoutEmployeesInput
  invited_by?: Prisma.EmployeesCreateNestedOneWithoutInvited_usersInput
  tenants?: Prisma.TenantsCreateNestedManyWithoutManagerInput
}

export type EmployeesUncheckedCreateWithoutInvited_usersInput = {
  id?: string
  tenant_id: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invited_by_id?: string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  tenants?: Prisma.TenantsUncheckedCreateNestedManyWithoutManagerInput
}

export type EmployeesCreateOrConnectWithoutInvited_usersInput = {
  where: Prisma.EmployeesWhereUniqueInput
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_usersInput, Prisma.EmployeesUncheckedCreateWithoutInvited_usersInput>
}

export type EmployeesCreateWithoutInvited_byInput = {
  id?: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  tenant: Prisma.TenantsCreateNestedOneWithoutEmployeesInput
  invited_users?: Prisma.EmployeesCreateNestedManyWithoutInvited_byInput
  tenants?: Prisma.TenantsCreateNestedManyWithoutManagerInput
}

export type EmployeesUncheckedCreateWithoutInvited_byInput = {
  id?: string
  tenant_id: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  invited_users?: Prisma.EmployeesUncheckedCreateNestedManyWithoutInvited_byInput
  tenants?: Prisma.TenantsUncheckedCreateNestedManyWithoutManagerInput
}

export type EmployeesCreateOrConnectWithoutInvited_byInput = {
  where: Prisma.EmployeesWhereUniqueInput
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_byInput, Prisma.EmployeesUncheckedCreateWithoutInvited_byInput>
}

export type EmployeesCreateManyInvited_byInputEnvelope = {
  data: Prisma.EmployeesCreateManyInvited_byInput | Prisma.EmployeesCreateManyInvited_byInput[]
  skipDuplicates?: boolean
}

export type EmployeesUpsertWithoutInvited_usersInput = {
  update: Prisma.XOR<Prisma.EmployeesUpdateWithoutInvited_usersInput, Prisma.EmployeesUncheckedUpdateWithoutInvited_usersInput>
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_usersInput, Prisma.EmployeesUncheckedCreateWithoutInvited_usersInput>
  where?: Prisma.EmployeesWhereInput
}

export type EmployeesUpdateToOneWithWhereWithoutInvited_usersInput = {
  where?: Prisma.EmployeesWhereInput
  data: Prisma.XOR<Prisma.EmployeesUpdateWithoutInvited_usersInput, Prisma.EmployeesUncheckedUpdateWithoutInvited_usersInput>
}

export type EmployeesUpdateWithoutInvited_usersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.TenantsUpdateOneRequiredWithoutEmployeesNestedInput
  invited_by?: Prisma.EmployeesUpdateOneWithoutInvited_usersNestedInput
  tenants?: Prisma.TenantsUpdateManyWithoutManagerNestedInput
}

export type EmployeesUncheckedUpdateWithoutInvited_usersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invited_by_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenants?: Prisma.TenantsUncheckedUpdateManyWithoutManagerNestedInput
}

export type EmployeesUpsertWithWhereUniqueWithoutInvited_byInput = {
  where: Prisma.EmployeesWhereUniqueInput
  update: Prisma.XOR<Prisma.EmployeesUpdateWithoutInvited_byInput, Prisma.EmployeesUncheckedUpdateWithoutInvited_byInput>
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutInvited_byInput, Prisma.EmployeesUncheckedCreateWithoutInvited_byInput>
}

export type EmployeesUpdateWithWhereUniqueWithoutInvited_byInput = {
  where: Prisma.EmployeesWhereUniqueInput
  data: Prisma.XOR<Prisma.EmployeesUpdateWithoutInvited_byInput, Prisma.EmployeesUncheckedUpdateWithoutInvited_byInput>
}

export type EmployeesUpdateManyWithWhereWithoutInvited_byInput = {
  where: Prisma.EmployeesScalarWhereInput
  data: Prisma.XOR<Prisma.EmployeesUpdateManyMutationInput, Prisma.EmployeesUncheckedUpdateManyWithoutInvited_byInput>
}

export type EmployeesScalarWhereInput = {
  AND?: Prisma.EmployeesScalarWhereInput | Prisma.EmployeesScalarWhereInput[]
  OR?: Prisma.EmployeesScalarWhereInput[]
  NOT?: Prisma.EmployeesScalarWhereInput | Prisma.EmployeesScalarWhereInput[]
  id?: Prisma.StringFilter<"Employees"> | string
  tenant_id?: Prisma.StringFilter<"Employees"> | string
  email?: Prisma.StringFilter<"Employees"> | string
  password_hash?: Prisma.StringNullableFilter<"Employees"> | string | null
  google_id?: Prisma.StringNullableFilter<"Employees"> | string | null
  name?: Prisma.StringFilter<"Employees"> | string
  avatar_url?: Prisma.StringNullableFilter<"Employees"> | string | null
  is_active?: Prisma.BoolFilter<"Employees"> | boolean
  is_manager?: Prisma.BoolFilter<"Employees"> | boolean
  deactivated_at?: Prisma.DateTimeNullableFilter<"Employees"> | Date | string | null
  invited_by_id?: Prisma.StringNullableFilter<"Employees"> | string | null
  invite_accepted_at?: Prisma.DateTimeNullableFilter<"Employees"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Employees"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Employees"> | Date | string
}

export type EmployeesCreateWithoutTenantInput = {
  id?: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  invited_by?: Prisma.EmployeesCreateNestedOneWithoutInvited_usersInput
  invited_users?: Prisma.EmployeesCreateNestedManyWithoutInvited_byInput
  tenants?: Prisma.TenantsCreateNestedManyWithoutManagerInput
}

export type EmployeesUncheckedCreateWithoutTenantInput = {
  id?: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invited_by_id?: string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  invited_users?: Prisma.EmployeesUncheckedCreateNestedManyWithoutInvited_byInput
  tenants?: Prisma.TenantsUncheckedCreateNestedManyWithoutManagerInput
}

export type EmployeesCreateOrConnectWithoutTenantInput = {
  where: Prisma.EmployeesWhereUniqueInput
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantInput, Prisma.EmployeesUncheckedCreateWithoutTenantInput>
}

export type EmployeesCreateManyTenantInputEnvelope = {
  data: Prisma.EmployeesCreateManyTenantInput | Prisma.EmployeesCreateManyTenantInput[]
  skipDuplicates?: boolean
}

export type EmployeesCreateWithoutTenantsInput = {
  id?: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  tenant: Prisma.TenantsCreateNestedOneWithoutEmployeesInput
  invited_by?: Prisma.EmployeesCreateNestedOneWithoutInvited_usersInput
  invited_users?: Prisma.EmployeesCreateNestedManyWithoutInvited_byInput
}

export type EmployeesUncheckedCreateWithoutTenantsInput = {
  id?: string
  tenant_id: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invited_by_id?: string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  invited_users?: Prisma.EmployeesUncheckedCreateNestedManyWithoutInvited_byInput
}

export type EmployeesCreateOrConnectWithoutTenantsInput = {
  where: Prisma.EmployeesWhereUniqueInput
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantsInput, Prisma.EmployeesUncheckedCreateWithoutTenantsInput>
}

export type EmployeesUpsertWithWhereUniqueWithoutTenantInput = {
  where: Prisma.EmployeesWhereUniqueInput
  update: Prisma.XOR<Prisma.EmployeesUpdateWithoutTenantInput, Prisma.EmployeesUncheckedUpdateWithoutTenantInput>
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantInput, Prisma.EmployeesUncheckedCreateWithoutTenantInput>
}

export type EmployeesUpdateWithWhereUniqueWithoutTenantInput = {
  where: Prisma.EmployeesWhereUniqueInput
  data: Prisma.XOR<Prisma.EmployeesUpdateWithoutTenantInput, Prisma.EmployeesUncheckedUpdateWithoutTenantInput>
}

export type EmployeesUpdateManyWithWhereWithoutTenantInput = {
  where: Prisma.EmployeesScalarWhereInput
  data: Prisma.XOR<Prisma.EmployeesUpdateManyMutationInput, Prisma.EmployeesUncheckedUpdateManyWithoutTenantInput>
}

export type EmployeesUpsertWithoutTenantsInput = {
  update: Prisma.XOR<Prisma.EmployeesUpdateWithoutTenantsInput, Prisma.EmployeesUncheckedUpdateWithoutTenantsInput>
  create: Prisma.XOR<Prisma.EmployeesCreateWithoutTenantsInput, Prisma.EmployeesUncheckedCreateWithoutTenantsInput>
  where?: Prisma.EmployeesWhereInput
}

export type EmployeesUpdateToOneWithWhereWithoutTenantsInput = {
  where?: Prisma.EmployeesWhereInput
  data: Prisma.XOR<Prisma.EmployeesUpdateWithoutTenantsInput, Prisma.EmployeesUncheckedUpdateWithoutTenantsInput>
}

export type EmployeesUpdateWithoutTenantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.TenantsUpdateOneRequiredWithoutEmployeesNestedInput
  invited_by?: Prisma.EmployeesUpdateOneWithoutInvited_usersNestedInput
  invited_users?: Prisma.EmployeesUpdateManyWithoutInvited_byNestedInput
}

export type EmployeesUncheckedUpdateWithoutTenantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invited_by_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invited_users?: Prisma.EmployeesUncheckedUpdateManyWithoutInvited_byNestedInput
}

export type EmployeesCreateManyInvited_byInput = {
  id?: string
  tenant_id: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type EmployeesUpdateWithoutInvited_byInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenant?: Prisma.TenantsUpdateOneRequiredWithoutEmployeesNestedInput
  invited_users?: Prisma.EmployeesUpdateManyWithoutInvited_byNestedInput
  tenants?: Prisma.TenantsUpdateManyWithoutManagerNestedInput
}

export type EmployeesUncheckedUpdateWithoutInvited_byInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invited_users?: Prisma.EmployeesUncheckedUpdateManyWithoutInvited_byNestedInput
  tenants?: Prisma.TenantsUncheckedUpdateManyWithoutManagerNestedInput
}

export type EmployeesUncheckedUpdateManyWithoutInvited_byInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmployeesCreateManyTenantInput = {
  id?: string
  email: string
  password_hash?: string | null
  google_id?: string | null
  name: string
  avatar_url?: string | null
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: Date | string | null
  invited_by_id?: string | null
  invite_accepted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type EmployeesUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invited_by?: Prisma.EmployeesUpdateOneWithoutInvited_usersNestedInput
  invited_users?: Prisma.EmployeesUpdateManyWithoutInvited_byNestedInput
  tenants?: Prisma.TenantsUpdateManyWithoutManagerNestedInput
}

export type EmployeesUncheckedUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invited_by_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invited_users?: Prisma.EmployeesUncheckedUpdateManyWithoutInvited_byNestedInput
  tenants?: Prisma.TenantsUncheckedUpdateManyWithoutManagerNestedInput
}

export type EmployeesUncheckedUpdateManyWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  google_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  avatar_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  is_manager?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deactivated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  invited_by_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  invite_accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type EmployeesCountOutputType
 */

export type EmployeesCountOutputType = {
  invited_users: number
  tenants: number
}

export type EmployeesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  invited_users?: boolean | EmployeesCountOutputTypeCountInvited_usersArgs
  tenants?: boolean | EmployeesCountOutputTypeCountTenantsArgs
}

/**
 * EmployeesCountOutputType without action
 */
export type EmployeesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmployeesCountOutputType
   */
  select?: Prisma.EmployeesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmployeesCountOutputType without action
 */
export type EmployeesCountOutputTypeCountInvited_usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmployeesWhereInput
}

/**
 * EmployeesCountOutputType without action
 */
export type EmployeesCountOutputTypeCountTenantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TenantsWhereInput
}


export type EmployeesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  password_hash?: boolean
  google_id?: boolean
  name?: boolean
  avatar_url?: boolean
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: boolean
  invited_by_id?: boolean
  invite_accepted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
  invited_by?: boolean | Prisma.Employees$invited_byArgs<ExtArgs>
  invited_users?: boolean | Prisma.Employees$invited_usersArgs<ExtArgs>
  tenants?: boolean | Prisma.Employees$tenantsArgs<ExtArgs>
  _count?: boolean | Prisma.EmployeesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employees"]>

export type EmployeesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  password_hash?: boolean
  google_id?: boolean
  name?: boolean
  avatar_url?: boolean
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: boolean
  invited_by_id?: boolean
  invite_accepted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
  invited_by?: boolean | Prisma.Employees$invited_byArgs<ExtArgs>
}, ExtArgs["result"]["employees"]>

export type EmployeesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  password_hash?: boolean
  google_id?: boolean
  name?: boolean
  avatar_url?: boolean
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: boolean
  invited_by_id?: boolean
  invite_accepted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
  invited_by?: boolean | Prisma.Employees$invited_byArgs<ExtArgs>
}, ExtArgs["result"]["employees"]>

export type EmployeesSelectScalar = {
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  password_hash?: boolean
  google_id?: boolean
  name?: boolean
  avatar_url?: boolean
  is_active?: boolean
  is_manager?: boolean
  deactivated_at?: boolean
  invited_by_id?: boolean
  invite_accepted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type EmployeesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tenant_id" | "email" | "password_hash" | "google_id" | "name" | "avatar_url" | "is_active" | "is_manager" | "deactivated_at" | "invited_by_id" | "invite_accepted_at" | "created_at" | "updated_at", ExtArgs["result"]["employees"]>
export type EmployeesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
  invited_by?: boolean | Prisma.Employees$invited_byArgs<ExtArgs>
  invited_users?: boolean | Prisma.Employees$invited_usersArgs<ExtArgs>
  tenants?: boolean | Prisma.Employees$tenantsArgs<ExtArgs>
  _count?: boolean | Prisma.EmployeesCountOutputTypeDefaultArgs<ExtArgs>
}
export type EmployeesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
  invited_by?: boolean | Prisma.Employees$invited_byArgs<ExtArgs>
}
export type EmployeesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
  invited_by?: boolean | Prisma.Employees$invited_byArgs<ExtArgs>
}

export type $EmployeesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Employees"
  objects: {
    tenant: Prisma.$TenantsPayload<ExtArgs>
    invited_by: Prisma.$EmployeesPayload<ExtArgs> | null
    invited_users: Prisma.$EmployeesPayload<ExtArgs>[]
    tenants: Prisma.$TenantsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tenant_id: string
    email: string
    password_hash: string | null
    google_id: string | null
    name: string
    avatar_url: string | null
    is_active: boolean
    is_manager: boolean
    deactivated_at: Date | null
    invited_by_id: string | null
    invite_accepted_at: Date | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["employees"]>
  composites: {}
}

export type EmployeesGetPayload<S extends boolean | null | undefined | EmployeesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmployeesPayload, S>

export type EmployeesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmployeesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmployeesCountAggregateInputType | true
  }

export interface EmployeesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Employees'], meta: { name: 'Employees' } }
  /**
   * Find zero or one Employees that matches the filter.
   * @param {EmployeesFindUniqueArgs} args - Arguments to find a Employees
   * @example
   * // Get one Employees
   * const employees = await prisma.employees.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmployeesFindUniqueArgs>(args: Prisma.SelectSubset<T, EmployeesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Employees that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmployeesFindUniqueOrThrowArgs} args - Arguments to find a Employees
   * @example
   * // Get one Employees
   * const employees = await prisma.employees.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmployeesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmployeesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employees that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeesFindFirstArgs} args - Arguments to find a Employees
   * @example
   * // Get one Employees
   * const employees = await prisma.employees.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmployeesFindFirstArgs>(args?: Prisma.SelectSubset<T, EmployeesFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Employees that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeesFindFirstOrThrowArgs} args - Arguments to find a Employees
   * @example
   * // Get one Employees
   * const employees = await prisma.employees.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmployeesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmployeesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Employees that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Employees
   * const employees = await prisma.employees.findMany()
   * 
   * // Get first 10 Employees
   * const employees = await prisma.employees.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const employeesWithIdOnly = await prisma.employees.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmployeesFindManyArgs>(args?: Prisma.SelectSubset<T, EmployeesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Employees.
   * @param {EmployeesCreateArgs} args - Arguments to create a Employees.
   * @example
   * // Create one Employees
   * const Employees = await prisma.employees.create({
   *   data: {
   *     // ... data to create a Employees
   *   }
   * })
   * 
   */
  create<T extends EmployeesCreateArgs>(args: Prisma.SelectSubset<T, EmployeesCreateArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Employees.
   * @param {EmployeesCreateManyArgs} args - Arguments to create many Employees.
   * @example
   * // Create many Employees
   * const employees = await prisma.employees.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmployeesCreateManyArgs>(args?: Prisma.SelectSubset<T, EmployeesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Employees and returns the data saved in the database.
   * @param {EmployeesCreateManyAndReturnArgs} args - Arguments to create many Employees.
   * @example
   * // Create many Employees
   * const employees = await prisma.employees.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Employees and only return the `id`
   * const employeesWithIdOnly = await prisma.employees.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmployeesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmployeesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Employees.
   * @param {EmployeesDeleteArgs} args - Arguments to delete one Employees.
   * @example
   * // Delete one Employees
   * const Employees = await prisma.employees.delete({
   *   where: {
   *     // ... filter to delete one Employees
   *   }
   * })
   * 
   */
  delete<T extends EmployeesDeleteArgs>(args: Prisma.SelectSubset<T, EmployeesDeleteArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Employees.
   * @param {EmployeesUpdateArgs} args - Arguments to update one Employees.
   * @example
   * // Update one Employees
   * const employees = await prisma.employees.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmployeesUpdateArgs>(args: Prisma.SelectSubset<T, EmployeesUpdateArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Employees.
   * @param {EmployeesDeleteManyArgs} args - Arguments to filter Employees to delete.
   * @example
   * // Delete a few Employees
   * const { count } = await prisma.employees.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmployeesDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmployeesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Employees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Employees
   * const employees = await prisma.employees.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmployeesUpdateManyArgs>(args: Prisma.SelectSubset<T, EmployeesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Employees and returns the data updated in the database.
   * @param {EmployeesUpdateManyAndReturnArgs} args - Arguments to update many Employees.
   * @example
   * // Update many Employees
   * const employees = await prisma.employees.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Employees and only return the `id`
   * const employeesWithIdOnly = await prisma.employees.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmployeesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmployeesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Employees.
   * @param {EmployeesUpsertArgs} args - Arguments to update or create a Employees.
   * @example
   * // Update or create a Employees
   * const employees = await prisma.employees.upsert({
   *   create: {
   *     // ... data to create a Employees
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Employees we want to update
   *   }
   * })
   */
  upsert<T extends EmployeesUpsertArgs>(args: Prisma.SelectSubset<T, EmployeesUpsertArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Employees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeesCountArgs} args - Arguments to filter Employees to count.
   * @example
   * // Count the number of Employees
   * const count = await prisma.employees.count({
   *   where: {
   *     // ... the filter for the Employees we want to count
   *   }
   * })
  **/
  count<T extends EmployeesCountArgs>(
    args?: Prisma.Subset<T, EmployeesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmployeesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Employees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmployeesAggregateArgs>(args: Prisma.Subset<T, EmployeesAggregateArgs>): Prisma.PrismaPromise<GetEmployeesAggregateType<T>>

  /**
   * Group by Employees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmployeesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmployeesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmployeesGroupByArgs['orderBy'] }
      : { orderBy?: EmployeesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmployeesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmployeesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Employees model
 */
readonly fields: EmployeesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Employees.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmployeesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tenant<T extends Prisma.TenantsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TenantsDefaultArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  invited_by<T extends Prisma.Employees$invited_byArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Employees$invited_byArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  invited_users<T extends Prisma.Employees$invited_usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Employees$invited_usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  tenants<T extends Prisma.Employees$tenantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Employees$tenantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Employees model
 */
export interface EmployeesFieldRefs {
  readonly id: Prisma.FieldRef<"Employees", 'String'>
  readonly tenant_id: Prisma.FieldRef<"Employees", 'String'>
  readonly email: Prisma.FieldRef<"Employees", 'String'>
  readonly password_hash: Prisma.FieldRef<"Employees", 'String'>
  readonly google_id: Prisma.FieldRef<"Employees", 'String'>
  readonly name: Prisma.FieldRef<"Employees", 'String'>
  readonly avatar_url: Prisma.FieldRef<"Employees", 'String'>
  readonly is_active: Prisma.FieldRef<"Employees", 'Boolean'>
  readonly is_manager: Prisma.FieldRef<"Employees", 'Boolean'>
  readonly deactivated_at: Prisma.FieldRef<"Employees", 'DateTime'>
  readonly invited_by_id: Prisma.FieldRef<"Employees", 'String'>
  readonly invite_accepted_at: Prisma.FieldRef<"Employees", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"Employees", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Employees", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Employees findUnique
 */
export type EmployeesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * Filter, which Employees to fetch.
   */
  where: Prisma.EmployeesWhereUniqueInput
}

/**
 * Employees findUniqueOrThrow
 */
export type EmployeesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * Filter, which Employees to fetch.
   */
  where: Prisma.EmployeesWhereUniqueInput
}

/**
 * Employees findFirst
 */
export type EmployeesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * Filter, which Employees to fetch.
   */
  where?: Prisma.EmployeesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employees to fetch.
   */
  orderBy?: Prisma.EmployeesOrderByWithRelationInput | Prisma.EmployeesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Employees.
   */
  cursor?: Prisma.EmployeesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Employees.
   */
  distinct?: Prisma.EmployeesScalarFieldEnum | Prisma.EmployeesScalarFieldEnum[]
}

/**
 * Employees findFirstOrThrow
 */
export type EmployeesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * Filter, which Employees to fetch.
   */
  where?: Prisma.EmployeesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employees to fetch.
   */
  orderBy?: Prisma.EmployeesOrderByWithRelationInput | Prisma.EmployeesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Employees.
   */
  cursor?: Prisma.EmployeesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Employees.
   */
  distinct?: Prisma.EmployeesScalarFieldEnum | Prisma.EmployeesScalarFieldEnum[]
}

/**
 * Employees findMany
 */
export type EmployeesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * Filter, which Employees to fetch.
   */
  where?: Prisma.EmployeesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Employees to fetch.
   */
  orderBy?: Prisma.EmployeesOrderByWithRelationInput | Prisma.EmployeesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Employees.
   */
  cursor?: Prisma.EmployeesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Employees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Employees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Employees.
   */
  distinct?: Prisma.EmployeesScalarFieldEnum | Prisma.EmployeesScalarFieldEnum[]
}

/**
 * Employees create
 */
export type EmployeesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * The data needed to create a Employees.
   */
  data: Prisma.XOR<Prisma.EmployeesCreateInput, Prisma.EmployeesUncheckedCreateInput>
}

/**
 * Employees createMany
 */
export type EmployeesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Employees.
   */
  data: Prisma.EmployeesCreateManyInput | Prisma.EmployeesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Employees createManyAndReturn
 */
export type EmployeesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * The data used to create many Employees.
   */
  data: Prisma.EmployeesCreateManyInput | Prisma.EmployeesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Employees update
 */
export type EmployeesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * The data needed to update a Employees.
   */
  data: Prisma.XOR<Prisma.EmployeesUpdateInput, Prisma.EmployeesUncheckedUpdateInput>
  /**
   * Choose, which Employees to update.
   */
  where: Prisma.EmployeesWhereUniqueInput
}

/**
 * Employees updateMany
 */
export type EmployeesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Employees.
   */
  data: Prisma.XOR<Prisma.EmployeesUpdateManyMutationInput, Prisma.EmployeesUncheckedUpdateManyInput>
  /**
   * Filter which Employees to update
   */
  where?: Prisma.EmployeesWhereInput
  /**
   * Limit how many Employees to update.
   */
  limit?: number
}

/**
 * Employees updateManyAndReturn
 */
export type EmployeesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * The data used to update Employees.
   */
  data: Prisma.XOR<Prisma.EmployeesUpdateManyMutationInput, Prisma.EmployeesUncheckedUpdateManyInput>
  /**
   * Filter which Employees to update
   */
  where?: Prisma.EmployeesWhereInput
  /**
   * Limit how many Employees to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Employees upsert
 */
export type EmployeesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * The filter to search for the Employees to update in case it exists.
   */
  where: Prisma.EmployeesWhereUniqueInput
  /**
   * In case the Employees found by the `where` argument doesn't exist, create a new Employees with this data.
   */
  create: Prisma.XOR<Prisma.EmployeesCreateInput, Prisma.EmployeesUncheckedCreateInput>
  /**
   * In case the Employees was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmployeesUpdateInput, Prisma.EmployeesUncheckedUpdateInput>
}

/**
 * Employees delete
 */
export type EmployeesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  /**
   * Filter which Employees to delete.
   */
  where: Prisma.EmployeesWhereUniqueInput
}

/**
 * Employees deleteMany
 */
export type EmployeesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Employees to delete
   */
  where?: Prisma.EmployeesWhereInput
  /**
   * Limit how many Employees to delete.
   */
  limit?: number
}

/**
 * Employees.invited_by
 */
export type Employees$invited_byArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  where?: Prisma.EmployeesWhereInput
}

/**
 * Employees.invited_users
 */
export type Employees$invited_usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  where?: Prisma.EmployeesWhereInput
  orderBy?: Prisma.EmployeesOrderByWithRelationInput | Prisma.EmployeesOrderByWithRelationInput[]
  cursor?: Prisma.EmployeesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmployeesScalarFieldEnum | Prisma.EmployeesScalarFieldEnum[]
}

/**
 * Employees.tenants
 */
export type Employees$tenantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  where?: Prisma.TenantsWhereInput
  orderBy?: Prisma.TenantsOrderByWithRelationInput | Prisma.TenantsOrderByWithRelationInput[]
  cursor?: Prisma.TenantsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TenantsScalarFieldEnum | Prisma.TenantsScalarFieldEnum[]
}

/**
 * Employees without action
 */
export type EmployeesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
}
