
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InviteLinks` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model InviteLinks
 * 
 */
export type InviteLinksModel = runtime.Types.Result.DefaultSelection<Prisma.$InviteLinksPayload>

export type AggregateInviteLinks = {
  _count: InviteLinksCountAggregateOutputType | null
  _min: InviteLinksMinAggregateOutputType | null
  _max: InviteLinksMaxAggregateOutputType | null
}

export type InviteLinksMinAggregateOutputType = {
  id: string | null
  tenant_id: string | null
  email: string | null
  token: string | null
  expires_at: Date | null
  accepted_at: Date | null
  created_by: string | null
  created_at: Date | null
  tenantsId: string | null
}

export type InviteLinksMaxAggregateOutputType = {
  id: string | null
  tenant_id: string | null
  email: string | null
  token: string | null
  expires_at: Date | null
  accepted_at: Date | null
  created_by: string | null
  created_at: Date | null
  tenantsId: string | null
}

export type InviteLinksCountAggregateOutputType = {
  id: number
  tenant_id: number
  email: number
  token: number
  expires_at: number
  accepted_at: number
  created_by: number
  created_at: number
  tenantsId: number
  _all: number
}


export type InviteLinksMinAggregateInputType = {
  id?: true
  tenant_id?: true
  email?: true
  token?: true
  expires_at?: true
  accepted_at?: true
  created_by?: true
  created_at?: true
  tenantsId?: true
}

export type InviteLinksMaxAggregateInputType = {
  id?: true
  tenant_id?: true
  email?: true
  token?: true
  expires_at?: true
  accepted_at?: true
  created_by?: true
  created_at?: true
  tenantsId?: true
}

export type InviteLinksCountAggregateInputType = {
  id?: true
  tenant_id?: true
  email?: true
  token?: true
  expires_at?: true
  accepted_at?: true
  created_by?: true
  created_at?: true
  tenantsId?: true
  _all?: true
}

export type InviteLinksAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InviteLinks to aggregate.
   */
  where?: Prisma.InviteLinksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InviteLinks to fetch.
   */
  orderBy?: Prisma.InviteLinksOrderByWithRelationInput | Prisma.InviteLinksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InviteLinksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InviteLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InviteLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InviteLinks
  **/
  _count?: true | InviteLinksCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InviteLinksMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InviteLinksMaxAggregateInputType
}

export type GetInviteLinksAggregateType<T extends InviteLinksAggregateArgs> = {
      [P in keyof T & keyof AggregateInviteLinks]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInviteLinks[P]>
    : Prisma.GetScalarType<T[P], AggregateInviteLinks[P]>
}




export type InviteLinksGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InviteLinksWhereInput
  orderBy?: Prisma.InviteLinksOrderByWithAggregationInput | Prisma.InviteLinksOrderByWithAggregationInput[]
  by: Prisma.InviteLinksScalarFieldEnum[] | Prisma.InviteLinksScalarFieldEnum
  having?: Prisma.InviteLinksScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InviteLinksCountAggregateInputType | true
  _min?: InviteLinksMinAggregateInputType
  _max?: InviteLinksMaxAggregateInputType
}

export type InviteLinksGroupByOutputType = {
  id: string
  tenant_id: string
  email: string
  token: string
  expires_at: Date
  accepted_at: Date | null
  created_by: string
  created_at: Date
  tenantsId: string | null
  _count: InviteLinksCountAggregateOutputType | null
  _min: InviteLinksMinAggregateOutputType | null
  _max: InviteLinksMaxAggregateOutputType | null
}

export type GetInviteLinksGroupByPayload<T extends InviteLinksGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InviteLinksGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InviteLinksGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InviteLinksGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InviteLinksGroupByOutputType[P]>
      }
    >
  >



export type InviteLinksWhereInput = {
  AND?: Prisma.InviteLinksWhereInput | Prisma.InviteLinksWhereInput[]
  OR?: Prisma.InviteLinksWhereInput[]
  NOT?: Prisma.InviteLinksWhereInput | Prisma.InviteLinksWhereInput[]
  id?: Prisma.StringFilter<"InviteLinks"> | string
  tenant_id?: Prisma.StringFilter<"InviteLinks"> | string
  email?: Prisma.StringFilter<"InviteLinks"> | string
  token?: Prisma.StringFilter<"InviteLinks"> | string
  expires_at?: Prisma.DateTimeFilter<"InviteLinks"> | Date | string
  accepted_at?: Prisma.DateTimeNullableFilter<"InviteLinks"> | Date | string | null
  created_by?: Prisma.StringFilter<"InviteLinks"> | string
  created_at?: Prisma.DateTimeFilter<"InviteLinks"> | Date | string
  tenantsId?: Prisma.StringNullableFilter<"InviteLinks"> | string | null
  tenant?: Prisma.XOR<Prisma.TenantsScalarRelationFilter, Prisma.TenantsWhereInput>
}

export type InviteLinksOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  accepted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  tenantsId?: Prisma.SortOrderInput | Prisma.SortOrder
  tenant?: Prisma.TenantsOrderByWithRelationInput
}

export type InviteLinksWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  token?: string
  AND?: Prisma.InviteLinksWhereInput | Prisma.InviteLinksWhereInput[]
  OR?: Prisma.InviteLinksWhereInput[]
  NOT?: Prisma.InviteLinksWhereInput | Prisma.InviteLinksWhereInput[]
  tenant_id?: Prisma.StringFilter<"InviteLinks"> | string
  email?: Prisma.StringFilter<"InviteLinks"> | string
  expires_at?: Prisma.DateTimeFilter<"InviteLinks"> | Date | string
  accepted_at?: Prisma.DateTimeNullableFilter<"InviteLinks"> | Date | string | null
  created_by?: Prisma.StringFilter<"InviteLinks"> | string
  created_at?: Prisma.DateTimeFilter<"InviteLinks"> | Date | string
  tenantsId?: Prisma.StringNullableFilter<"InviteLinks"> | string | null
  tenant?: Prisma.XOR<Prisma.TenantsScalarRelationFilter, Prisma.TenantsWhereInput>
}, "id" | "token">

export type InviteLinksOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  accepted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  tenantsId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.InviteLinksCountOrderByAggregateInput
  _max?: Prisma.InviteLinksMaxOrderByAggregateInput
  _min?: Prisma.InviteLinksMinOrderByAggregateInput
}

export type InviteLinksScalarWhereWithAggregatesInput = {
  AND?: Prisma.InviteLinksScalarWhereWithAggregatesInput | Prisma.InviteLinksScalarWhereWithAggregatesInput[]
  OR?: Prisma.InviteLinksScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InviteLinksScalarWhereWithAggregatesInput | Prisma.InviteLinksScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InviteLinks"> | string
  tenant_id?: Prisma.StringWithAggregatesFilter<"InviteLinks"> | string
  email?: Prisma.StringWithAggregatesFilter<"InviteLinks"> | string
  token?: Prisma.StringWithAggregatesFilter<"InviteLinks"> | string
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"InviteLinks"> | Date | string
  accepted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"InviteLinks"> | Date | string | null
  created_by?: Prisma.StringWithAggregatesFilter<"InviteLinks"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"InviteLinks"> | Date | string
  tenantsId?: Prisma.StringNullableWithAggregatesFilter<"InviteLinks"> | string | null
}

export type InviteLinksCreateInput = {
  id?: string
  email: string
  token: string
  expires_at: Date | string
  accepted_at?: Date | string | null
  created_by: string
  created_at?: Date | string
  tenantsId?: string | null
  tenant: Prisma.TenantsCreateNestedOneWithoutInviteLinksInput
}

export type InviteLinksUncheckedCreateInput = {
  id?: string
  tenant_id: string
  email: string
  token: string
  expires_at: Date | string
  accepted_at?: Date | string | null
  created_by: string
  created_at?: Date | string
  tenantsId?: string | null
}

export type InviteLinksUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantsId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tenant?: Prisma.TenantsUpdateOneRequiredWithoutInviteLinksNestedInput
}

export type InviteLinksUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantsId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InviteLinksCreateManyInput = {
  id?: string
  tenant_id: string
  email: string
  token: string
  expires_at: Date | string
  accepted_at?: Date | string | null
  created_by: string
  created_at?: Date | string
  tenantsId?: string | null
}

export type InviteLinksUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantsId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InviteLinksUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenant_id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantsId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InviteLinksListRelationFilter = {
  every?: Prisma.InviteLinksWhereInput
  some?: Prisma.InviteLinksWhereInput
  none?: Prisma.InviteLinksWhereInput
}

export type InviteLinksOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InviteLinksCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  accepted_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  tenantsId?: Prisma.SortOrder
}

export type InviteLinksMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  accepted_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  tenantsId?: Prisma.SortOrder
}

export type InviteLinksMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenant_id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  accepted_at?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  tenantsId?: Prisma.SortOrder
}

export type InviteLinksCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.InviteLinksCreateWithoutTenantInput, Prisma.InviteLinksUncheckedCreateWithoutTenantInput> | Prisma.InviteLinksCreateWithoutTenantInput[] | Prisma.InviteLinksUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.InviteLinksCreateOrConnectWithoutTenantInput | Prisma.InviteLinksCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.InviteLinksCreateManyTenantInputEnvelope
  connect?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
}

export type InviteLinksUncheckedCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.InviteLinksCreateWithoutTenantInput, Prisma.InviteLinksUncheckedCreateWithoutTenantInput> | Prisma.InviteLinksCreateWithoutTenantInput[] | Prisma.InviteLinksUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.InviteLinksCreateOrConnectWithoutTenantInput | Prisma.InviteLinksCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.InviteLinksCreateManyTenantInputEnvelope
  connect?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
}

export type InviteLinksUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.InviteLinksCreateWithoutTenantInput, Prisma.InviteLinksUncheckedCreateWithoutTenantInput> | Prisma.InviteLinksCreateWithoutTenantInput[] | Prisma.InviteLinksUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.InviteLinksCreateOrConnectWithoutTenantInput | Prisma.InviteLinksCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.InviteLinksUpsertWithWhereUniqueWithoutTenantInput | Prisma.InviteLinksUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.InviteLinksCreateManyTenantInputEnvelope
  set?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  disconnect?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  delete?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  connect?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  update?: Prisma.InviteLinksUpdateWithWhereUniqueWithoutTenantInput | Prisma.InviteLinksUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.InviteLinksUpdateManyWithWhereWithoutTenantInput | Prisma.InviteLinksUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.InviteLinksScalarWhereInput | Prisma.InviteLinksScalarWhereInput[]
}

export type InviteLinksUncheckedUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.InviteLinksCreateWithoutTenantInput, Prisma.InviteLinksUncheckedCreateWithoutTenantInput> | Prisma.InviteLinksCreateWithoutTenantInput[] | Prisma.InviteLinksUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.InviteLinksCreateOrConnectWithoutTenantInput | Prisma.InviteLinksCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.InviteLinksUpsertWithWhereUniqueWithoutTenantInput | Prisma.InviteLinksUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.InviteLinksCreateManyTenantInputEnvelope
  set?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  disconnect?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  delete?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  connect?: Prisma.InviteLinksWhereUniqueInput | Prisma.InviteLinksWhereUniqueInput[]
  update?: Prisma.InviteLinksUpdateWithWhereUniqueWithoutTenantInput | Prisma.InviteLinksUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.InviteLinksUpdateManyWithWhereWithoutTenantInput | Prisma.InviteLinksUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.InviteLinksScalarWhereInput | Prisma.InviteLinksScalarWhereInput[]
}

export type InviteLinksCreateWithoutTenantInput = {
  id?: string
  email: string
  token: string
  expires_at: Date | string
  accepted_at?: Date | string | null
  created_by: string
  created_at?: Date | string
  tenantsId?: string | null
}

export type InviteLinksUncheckedCreateWithoutTenantInput = {
  id?: string
  email: string
  token: string
  expires_at: Date | string
  accepted_at?: Date | string | null
  created_by: string
  created_at?: Date | string
  tenantsId?: string | null
}

export type InviteLinksCreateOrConnectWithoutTenantInput = {
  where: Prisma.InviteLinksWhereUniqueInput
  create: Prisma.XOR<Prisma.InviteLinksCreateWithoutTenantInput, Prisma.InviteLinksUncheckedCreateWithoutTenantInput>
}

export type InviteLinksCreateManyTenantInputEnvelope = {
  data: Prisma.InviteLinksCreateManyTenantInput | Prisma.InviteLinksCreateManyTenantInput[]
  skipDuplicates?: boolean
}

export type InviteLinksUpsertWithWhereUniqueWithoutTenantInput = {
  where: Prisma.InviteLinksWhereUniqueInput
  update: Prisma.XOR<Prisma.InviteLinksUpdateWithoutTenantInput, Prisma.InviteLinksUncheckedUpdateWithoutTenantInput>
  create: Prisma.XOR<Prisma.InviteLinksCreateWithoutTenantInput, Prisma.InviteLinksUncheckedCreateWithoutTenantInput>
}

export type InviteLinksUpdateWithWhereUniqueWithoutTenantInput = {
  where: Prisma.InviteLinksWhereUniqueInput
  data: Prisma.XOR<Prisma.InviteLinksUpdateWithoutTenantInput, Prisma.InviteLinksUncheckedUpdateWithoutTenantInput>
}

export type InviteLinksUpdateManyWithWhereWithoutTenantInput = {
  where: Prisma.InviteLinksScalarWhereInput
  data: Prisma.XOR<Prisma.InviteLinksUpdateManyMutationInput, Prisma.InviteLinksUncheckedUpdateManyWithoutTenantInput>
}

export type InviteLinksScalarWhereInput = {
  AND?: Prisma.InviteLinksScalarWhereInput | Prisma.InviteLinksScalarWhereInput[]
  OR?: Prisma.InviteLinksScalarWhereInput[]
  NOT?: Prisma.InviteLinksScalarWhereInput | Prisma.InviteLinksScalarWhereInput[]
  id?: Prisma.StringFilter<"InviteLinks"> | string
  tenant_id?: Prisma.StringFilter<"InviteLinks"> | string
  email?: Prisma.StringFilter<"InviteLinks"> | string
  token?: Prisma.StringFilter<"InviteLinks"> | string
  expires_at?: Prisma.DateTimeFilter<"InviteLinks"> | Date | string
  accepted_at?: Prisma.DateTimeNullableFilter<"InviteLinks"> | Date | string | null
  created_by?: Prisma.StringFilter<"InviteLinks"> | string
  created_at?: Prisma.DateTimeFilter<"InviteLinks"> | Date | string
  tenantsId?: Prisma.StringNullableFilter<"InviteLinks"> | string | null
}

export type InviteLinksCreateManyTenantInput = {
  id?: string
  email: string
  token: string
  expires_at: Date | string
  accepted_at?: Date | string | null
  created_by: string
  created_at?: Date | string
  tenantsId?: string | null
}

export type InviteLinksUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantsId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InviteLinksUncheckedUpdateWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantsId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InviteLinksUncheckedUpdateManyWithoutTenantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accepted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tenantsId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type InviteLinksSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  token?: boolean
  expires_at?: boolean
  accepted_at?: boolean
  created_by?: boolean
  created_at?: boolean
  tenantsId?: boolean
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inviteLinks"]>

export type InviteLinksSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  token?: boolean
  expires_at?: boolean
  accepted_at?: boolean
  created_by?: boolean
  created_at?: boolean
  tenantsId?: boolean
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inviteLinks"]>

export type InviteLinksSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  token?: boolean
  expires_at?: boolean
  accepted_at?: boolean
  created_by?: boolean
  created_at?: boolean
  tenantsId?: boolean
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inviteLinks"]>

export type InviteLinksSelectScalar = {
  id?: boolean
  tenant_id?: boolean
  email?: boolean
  token?: boolean
  expires_at?: boolean
  accepted_at?: boolean
  created_by?: boolean
  created_at?: boolean
  tenantsId?: boolean
}

export type InviteLinksOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tenant_id" | "email" | "token" | "expires_at" | "accepted_at" | "created_by" | "created_at" | "tenantsId", ExtArgs["result"]["inviteLinks"]>
export type InviteLinksInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
}
export type InviteLinksIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
}
export type InviteLinksIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tenant?: boolean | Prisma.TenantsDefaultArgs<ExtArgs>
}

export type $InviteLinksPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InviteLinks"
  objects: {
    tenant: Prisma.$TenantsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tenant_id: string
    email: string
    token: string
    expires_at: Date
    accepted_at: Date | null
    created_by: string
    created_at: Date
    tenantsId: string | null
  }, ExtArgs["result"]["inviteLinks"]>
  composites: {}
}

export type InviteLinksGetPayload<S extends boolean | null | undefined | InviteLinksDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload, S>

export type InviteLinksCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InviteLinksFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InviteLinksCountAggregateInputType | true
  }

export interface InviteLinksDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InviteLinks'], meta: { name: 'InviteLinks' } }
  /**
   * Find zero or one InviteLinks that matches the filter.
   * @param {InviteLinksFindUniqueArgs} args - Arguments to find a InviteLinks
   * @example
   * // Get one InviteLinks
   * const inviteLinks = await prisma.inviteLinks.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InviteLinksFindUniqueArgs>(args: Prisma.SelectSubset<T, InviteLinksFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InviteLinks that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InviteLinksFindUniqueOrThrowArgs} args - Arguments to find a InviteLinks
   * @example
   * // Get one InviteLinks
   * const inviteLinks = await prisma.inviteLinks.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InviteLinksFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InviteLinksFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InviteLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InviteLinksFindFirstArgs} args - Arguments to find a InviteLinks
   * @example
   * // Get one InviteLinks
   * const inviteLinks = await prisma.inviteLinks.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InviteLinksFindFirstArgs>(args?: Prisma.SelectSubset<T, InviteLinksFindFirstArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InviteLinks that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InviteLinksFindFirstOrThrowArgs} args - Arguments to find a InviteLinks
   * @example
   * // Get one InviteLinks
   * const inviteLinks = await prisma.inviteLinks.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InviteLinksFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InviteLinksFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InviteLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InviteLinksFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InviteLinks
   * const inviteLinks = await prisma.inviteLinks.findMany()
   * 
   * // Get first 10 InviteLinks
   * const inviteLinks = await prisma.inviteLinks.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inviteLinksWithIdOnly = await prisma.inviteLinks.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InviteLinksFindManyArgs>(args?: Prisma.SelectSubset<T, InviteLinksFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InviteLinks.
   * @param {InviteLinksCreateArgs} args - Arguments to create a InviteLinks.
   * @example
   * // Create one InviteLinks
   * const InviteLinks = await prisma.inviteLinks.create({
   *   data: {
   *     // ... data to create a InviteLinks
   *   }
   * })
   * 
   */
  create<T extends InviteLinksCreateArgs>(args: Prisma.SelectSubset<T, InviteLinksCreateArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InviteLinks.
   * @param {InviteLinksCreateManyArgs} args - Arguments to create many InviteLinks.
   * @example
   * // Create many InviteLinks
   * const inviteLinks = await prisma.inviteLinks.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InviteLinksCreateManyArgs>(args?: Prisma.SelectSubset<T, InviteLinksCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InviteLinks and returns the data saved in the database.
   * @param {InviteLinksCreateManyAndReturnArgs} args - Arguments to create many InviteLinks.
   * @example
   * // Create many InviteLinks
   * const inviteLinks = await prisma.inviteLinks.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InviteLinks and only return the `id`
   * const inviteLinksWithIdOnly = await prisma.inviteLinks.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InviteLinksCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InviteLinksCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InviteLinks.
   * @param {InviteLinksDeleteArgs} args - Arguments to delete one InviteLinks.
   * @example
   * // Delete one InviteLinks
   * const InviteLinks = await prisma.inviteLinks.delete({
   *   where: {
   *     // ... filter to delete one InviteLinks
   *   }
   * })
   * 
   */
  delete<T extends InviteLinksDeleteArgs>(args: Prisma.SelectSubset<T, InviteLinksDeleteArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InviteLinks.
   * @param {InviteLinksUpdateArgs} args - Arguments to update one InviteLinks.
   * @example
   * // Update one InviteLinks
   * const inviteLinks = await prisma.inviteLinks.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InviteLinksUpdateArgs>(args: Prisma.SelectSubset<T, InviteLinksUpdateArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InviteLinks.
   * @param {InviteLinksDeleteManyArgs} args - Arguments to filter InviteLinks to delete.
   * @example
   * // Delete a few InviteLinks
   * const { count } = await prisma.inviteLinks.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InviteLinksDeleteManyArgs>(args?: Prisma.SelectSubset<T, InviteLinksDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InviteLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InviteLinksUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InviteLinks
   * const inviteLinks = await prisma.inviteLinks.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InviteLinksUpdateManyArgs>(args: Prisma.SelectSubset<T, InviteLinksUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InviteLinks and returns the data updated in the database.
   * @param {InviteLinksUpdateManyAndReturnArgs} args - Arguments to update many InviteLinks.
   * @example
   * // Update many InviteLinks
   * const inviteLinks = await prisma.inviteLinks.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InviteLinks and only return the `id`
   * const inviteLinksWithIdOnly = await prisma.inviteLinks.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InviteLinksUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InviteLinksUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InviteLinks.
   * @param {InviteLinksUpsertArgs} args - Arguments to update or create a InviteLinks.
   * @example
   * // Update or create a InviteLinks
   * const inviteLinks = await prisma.inviteLinks.upsert({
   *   create: {
   *     // ... data to create a InviteLinks
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InviteLinks we want to update
   *   }
   * })
   */
  upsert<T extends InviteLinksUpsertArgs>(args: Prisma.SelectSubset<T, InviteLinksUpsertArgs<ExtArgs>>): Prisma.Prisma__InviteLinksClient<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InviteLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InviteLinksCountArgs} args - Arguments to filter InviteLinks to count.
   * @example
   * // Count the number of InviteLinks
   * const count = await prisma.inviteLinks.count({
   *   where: {
   *     // ... the filter for the InviteLinks we want to count
   *   }
   * })
  **/
  count<T extends InviteLinksCountArgs>(
    args?: Prisma.Subset<T, InviteLinksCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InviteLinksCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InviteLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InviteLinksAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InviteLinksAggregateArgs>(args: Prisma.Subset<T, InviteLinksAggregateArgs>): Prisma.PrismaPromise<GetInviteLinksAggregateType<T>>

  /**
   * Group by InviteLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InviteLinksGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InviteLinksGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InviteLinksGroupByArgs['orderBy'] }
      : { orderBy?: InviteLinksGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InviteLinksGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInviteLinksGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InviteLinks model
 */
readonly fields: InviteLinksFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InviteLinks.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InviteLinksClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tenant<T extends Prisma.TenantsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TenantsDefaultArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InviteLinks model
 */
export interface InviteLinksFieldRefs {
  readonly id: Prisma.FieldRef<"InviteLinks", 'String'>
  readonly tenant_id: Prisma.FieldRef<"InviteLinks", 'String'>
  readonly email: Prisma.FieldRef<"InviteLinks", 'String'>
  readonly token: Prisma.FieldRef<"InviteLinks", 'String'>
  readonly expires_at: Prisma.FieldRef<"InviteLinks", 'DateTime'>
  readonly accepted_at: Prisma.FieldRef<"InviteLinks", 'DateTime'>
  readonly created_by: Prisma.FieldRef<"InviteLinks", 'String'>
  readonly created_at: Prisma.FieldRef<"InviteLinks", 'DateTime'>
  readonly tenantsId: Prisma.FieldRef<"InviteLinks", 'String'>
}
    

// Custom InputTypes
/**
 * InviteLinks findUnique
 */
export type InviteLinksFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * Filter, which InviteLinks to fetch.
   */
  where: Prisma.InviteLinksWhereUniqueInput
}

/**
 * InviteLinks findUniqueOrThrow
 */
export type InviteLinksFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * Filter, which InviteLinks to fetch.
   */
  where: Prisma.InviteLinksWhereUniqueInput
}

/**
 * InviteLinks findFirst
 */
export type InviteLinksFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * Filter, which InviteLinks to fetch.
   */
  where?: Prisma.InviteLinksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InviteLinks to fetch.
   */
  orderBy?: Prisma.InviteLinksOrderByWithRelationInput | Prisma.InviteLinksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InviteLinks.
   */
  cursor?: Prisma.InviteLinksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InviteLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InviteLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InviteLinks.
   */
  distinct?: Prisma.InviteLinksScalarFieldEnum | Prisma.InviteLinksScalarFieldEnum[]
}

/**
 * InviteLinks findFirstOrThrow
 */
export type InviteLinksFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * Filter, which InviteLinks to fetch.
   */
  where?: Prisma.InviteLinksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InviteLinks to fetch.
   */
  orderBy?: Prisma.InviteLinksOrderByWithRelationInput | Prisma.InviteLinksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InviteLinks.
   */
  cursor?: Prisma.InviteLinksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InviteLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InviteLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InviteLinks.
   */
  distinct?: Prisma.InviteLinksScalarFieldEnum | Prisma.InviteLinksScalarFieldEnum[]
}

/**
 * InviteLinks findMany
 */
export type InviteLinksFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * Filter, which InviteLinks to fetch.
   */
  where?: Prisma.InviteLinksWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InviteLinks to fetch.
   */
  orderBy?: Prisma.InviteLinksOrderByWithRelationInput | Prisma.InviteLinksOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InviteLinks.
   */
  cursor?: Prisma.InviteLinksWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InviteLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InviteLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InviteLinks.
   */
  distinct?: Prisma.InviteLinksScalarFieldEnum | Prisma.InviteLinksScalarFieldEnum[]
}

/**
 * InviteLinks create
 */
export type InviteLinksCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * The data needed to create a InviteLinks.
   */
  data: Prisma.XOR<Prisma.InviteLinksCreateInput, Prisma.InviteLinksUncheckedCreateInput>
}

/**
 * InviteLinks createMany
 */
export type InviteLinksCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InviteLinks.
   */
  data: Prisma.InviteLinksCreateManyInput | Prisma.InviteLinksCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InviteLinks createManyAndReturn
 */
export type InviteLinksCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * The data used to create many InviteLinks.
   */
  data: Prisma.InviteLinksCreateManyInput | Prisma.InviteLinksCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InviteLinks update
 */
export type InviteLinksUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * The data needed to update a InviteLinks.
   */
  data: Prisma.XOR<Prisma.InviteLinksUpdateInput, Prisma.InviteLinksUncheckedUpdateInput>
  /**
   * Choose, which InviteLinks to update.
   */
  where: Prisma.InviteLinksWhereUniqueInput
}

/**
 * InviteLinks updateMany
 */
export type InviteLinksUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InviteLinks.
   */
  data: Prisma.XOR<Prisma.InviteLinksUpdateManyMutationInput, Prisma.InviteLinksUncheckedUpdateManyInput>
  /**
   * Filter which InviteLinks to update
   */
  where?: Prisma.InviteLinksWhereInput
  /**
   * Limit how many InviteLinks to update.
   */
  limit?: number
}

/**
 * InviteLinks updateManyAndReturn
 */
export type InviteLinksUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * The data used to update InviteLinks.
   */
  data: Prisma.XOR<Prisma.InviteLinksUpdateManyMutationInput, Prisma.InviteLinksUncheckedUpdateManyInput>
  /**
   * Filter which InviteLinks to update
   */
  where?: Prisma.InviteLinksWhereInput
  /**
   * Limit how many InviteLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InviteLinks upsert
 */
export type InviteLinksUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * The filter to search for the InviteLinks to update in case it exists.
   */
  where: Prisma.InviteLinksWhereUniqueInput
  /**
   * In case the InviteLinks found by the `where` argument doesn't exist, create a new InviteLinks with this data.
   */
  create: Prisma.XOR<Prisma.InviteLinksCreateInput, Prisma.InviteLinksUncheckedCreateInput>
  /**
   * In case the InviteLinks was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InviteLinksUpdateInput, Prisma.InviteLinksUncheckedUpdateInput>
}

/**
 * InviteLinks delete
 */
export type InviteLinksDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  /**
   * Filter which InviteLinks to delete.
   */
  where: Prisma.InviteLinksWhereUniqueInput
}

/**
 * InviteLinks deleteMany
 */
export type InviteLinksDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InviteLinks to delete
   */
  where?: Prisma.InviteLinksWhereInput
  /**
   * Limit how many InviteLinks to delete.
   */
  limit?: number
}

/**
 * InviteLinks without action
 */
export type InviteLinksDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
}
