
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SystemAdmins` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SystemAdmins
 * 
 */
export type SystemAdminsModel = runtime.Types.Result.DefaultSelection<Prisma.$SystemAdminsPayload>

export type AggregateSystemAdmins = {
  _count: SystemAdminsCountAggregateOutputType | null
  _min: SystemAdminsMinAggregateOutputType | null
  _max: SystemAdminsMaxAggregateOutputType | null
}

export type SystemAdminsMinAggregateOutputType = {
  id: string | null
  email: string | null
  name: string | null
  password_hash: string | null
  created_at: Date | null
  updated_at: Date | null
  is_active: boolean | null
}

export type SystemAdminsMaxAggregateOutputType = {
  id: string | null
  email: string | null
  name: string | null
  password_hash: string | null
  created_at: Date | null
  updated_at: Date | null
  is_active: boolean | null
}

export type SystemAdminsCountAggregateOutputType = {
  id: number
  email: number
  name: number
  password_hash: number
  created_at: number
  updated_at: number
  is_active: number
  _all: number
}


export type SystemAdminsMinAggregateInputType = {
  id?: true
  email?: true
  name?: true
  password_hash?: true
  created_at?: true
  updated_at?: true
  is_active?: true
}

export type SystemAdminsMaxAggregateInputType = {
  id?: true
  email?: true
  name?: true
  password_hash?: true
  created_at?: true
  updated_at?: true
  is_active?: true
}

export type SystemAdminsCountAggregateInputType = {
  id?: true
  email?: true
  name?: true
  password_hash?: true
  created_at?: true
  updated_at?: true
  is_active?: true
  _all?: true
}

export type SystemAdminsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SystemAdmins to aggregate.
   */
  where?: Prisma.SystemAdminsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SystemAdmins to fetch.
   */
  orderBy?: Prisma.SystemAdminsOrderByWithRelationInput | Prisma.SystemAdminsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SystemAdminsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SystemAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SystemAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SystemAdmins
  **/
  _count?: true | SystemAdminsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SystemAdminsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SystemAdminsMaxAggregateInputType
}

export type GetSystemAdminsAggregateType<T extends SystemAdminsAggregateArgs> = {
      [P in keyof T & keyof AggregateSystemAdmins]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSystemAdmins[P]>
    : Prisma.GetScalarType<T[P], AggregateSystemAdmins[P]>
}




export type SystemAdminsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SystemAdminsWhereInput
  orderBy?: Prisma.SystemAdminsOrderByWithAggregationInput | Prisma.SystemAdminsOrderByWithAggregationInput[]
  by: Prisma.SystemAdminsScalarFieldEnum[] | Prisma.SystemAdminsScalarFieldEnum
  having?: Prisma.SystemAdminsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SystemAdminsCountAggregateInputType | true
  _min?: SystemAdminsMinAggregateInputType
  _max?: SystemAdminsMaxAggregateInputType
}

export type SystemAdminsGroupByOutputType = {
  id: string
  email: string
  name: string
  password_hash: string
  created_at: Date
  updated_at: Date
  is_active: boolean
  _count: SystemAdminsCountAggregateOutputType | null
  _min: SystemAdminsMinAggregateOutputType | null
  _max: SystemAdminsMaxAggregateOutputType | null
}

export type GetSystemAdminsGroupByPayload<T extends SystemAdminsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SystemAdminsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SystemAdminsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SystemAdminsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SystemAdminsGroupByOutputType[P]>
      }
    >
  >



export type SystemAdminsWhereInput = {
  AND?: Prisma.SystemAdminsWhereInput | Prisma.SystemAdminsWhereInput[]
  OR?: Prisma.SystemAdminsWhereInput[]
  NOT?: Prisma.SystemAdminsWhereInput | Prisma.SystemAdminsWhereInput[]
  id?: Prisma.StringFilter<"SystemAdmins"> | string
  email?: Prisma.StringFilter<"SystemAdmins"> | string
  name?: Prisma.StringFilter<"SystemAdmins"> | string
  password_hash?: Prisma.StringFilter<"SystemAdmins"> | string
  created_at?: Prisma.DateTimeFilter<"SystemAdmins"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"SystemAdmins"> | Date | string
  is_active?: Prisma.BoolFilter<"SystemAdmins"> | boolean
}

export type SystemAdminsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type SystemAdminsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.SystemAdminsWhereInput | Prisma.SystemAdminsWhereInput[]
  OR?: Prisma.SystemAdminsWhereInput[]
  NOT?: Prisma.SystemAdminsWhereInput | Prisma.SystemAdminsWhereInput[]
  name?: Prisma.StringFilter<"SystemAdmins"> | string
  password_hash?: Prisma.StringFilter<"SystemAdmins"> | string
  created_at?: Prisma.DateTimeFilter<"SystemAdmins"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"SystemAdmins"> | Date | string
  is_active?: Prisma.BoolFilter<"SystemAdmins"> | boolean
}, "id" | "email">

export type SystemAdminsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
  _count?: Prisma.SystemAdminsCountOrderByAggregateInput
  _max?: Prisma.SystemAdminsMaxOrderByAggregateInput
  _min?: Prisma.SystemAdminsMinOrderByAggregateInput
}

export type SystemAdminsScalarWhereWithAggregatesInput = {
  AND?: Prisma.SystemAdminsScalarWhereWithAggregatesInput | Prisma.SystemAdminsScalarWhereWithAggregatesInput[]
  OR?: Prisma.SystemAdminsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SystemAdminsScalarWhereWithAggregatesInput | Prisma.SystemAdminsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SystemAdmins"> | string
  email?: Prisma.StringWithAggregatesFilter<"SystemAdmins"> | string
  name?: Prisma.StringWithAggregatesFilter<"SystemAdmins"> | string
  password_hash?: Prisma.StringWithAggregatesFilter<"SystemAdmins"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"SystemAdmins"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"SystemAdmins"> | Date | string
  is_active?: Prisma.BoolWithAggregatesFilter<"SystemAdmins"> | boolean
}

export type SystemAdminsCreateInput = {
  id?: string
  email: string
  name: string
  password_hash: string
  created_at?: Date | string
  updated_at?: Date | string
  is_active?: boolean
}

export type SystemAdminsUncheckedCreateInput = {
  id?: string
  email: string
  name: string
  password_hash: string
  created_at?: Date | string
  updated_at?: Date | string
  is_active?: boolean
}

export type SystemAdminsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SystemAdminsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SystemAdminsCreateManyInput = {
  id?: string
  email: string
  name: string
  password_hash: string
  created_at?: Date | string
  updated_at?: Date | string
  is_active?: boolean
}

export type SystemAdminsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SystemAdminsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  password_hash?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  is_active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SystemAdminsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type SystemAdminsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type SystemAdminsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  name?: Prisma.SortOrder
  password_hash?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  is_active?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}



export type SystemAdminsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  password_hash?: boolean
  created_at?: boolean
  updated_at?: boolean
  is_active?: boolean
}, ExtArgs["result"]["systemAdmins"]>

export type SystemAdminsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  password_hash?: boolean
  created_at?: boolean
  updated_at?: boolean
  is_active?: boolean
}, ExtArgs["result"]["systemAdmins"]>

export type SystemAdminsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  name?: boolean
  password_hash?: boolean
  created_at?: boolean
  updated_at?: boolean
  is_active?: boolean
}, ExtArgs["result"]["systemAdmins"]>

export type SystemAdminsSelectScalar = {
  id?: boolean
  email?: boolean
  name?: boolean
  password_hash?: boolean
  created_at?: boolean
  updated_at?: boolean
  is_active?: boolean
}

export type SystemAdminsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "name" | "password_hash" | "created_at" | "updated_at" | "is_active", ExtArgs["result"]["systemAdmins"]>

export type $SystemAdminsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SystemAdmins"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string
    name: string
    password_hash: string
    created_at: Date
    updated_at: Date
    is_active: boolean
  }, ExtArgs["result"]["systemAdmins"]>
  composites: {}
}

export type SystemAdminsGetPayload<S extends boolean | null | undefined | SystemAdminsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload, S>

export type SystemAdminsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SystemAdminsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SystemAdminsCountAggregateInputType | true
  }

export interface SystemAdminsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SystemAdmins'], meta: { name: 'SystemAdmins' } }
  /**
   * Find zero or one SystemAdmins that matches the filter.
   * @param {SystemAdminsFindUniqueArgs} args - Arguments to find a SystemAdmins
   * @example
   * // Get one SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SystemAdminsFindUniqueArgs>(args: Prisma.SelectSubset<T, SystemAdminsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SystemAdmins that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SystemAdminsFindUniqueOrThrowArgs} args - Arguments to find a SystemAdmins
   * @example
   * // Get one SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SystemAdminsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SystemAdminsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SystemAdmins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SystemAdminsFindFirstArgs} args - Arguments to find a SystemAdmins
   * @example
   * // Get one SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SystemAdminsFindFirstArgs>(args?: Prisma.SelectSubset<T, SystemAdminsFindFirstArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SystemAdmins that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SystemAdminsFindFirstOrThrowArgs} args - Arguments to find a SystemAdmins
   * @example
   * // Get one SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SystemAdminsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SystemAdminsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SystemAdmins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SystemAdminsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.findMany()
   * 
   * // Get first 10 SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const systemAdminsWithIdOnly = await prisma.systemAdmins.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SystemAdminsFindManyArgs>(args?: Prisma.SelectSubset<T, SystemAdminsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SystemAdmins.
   * @param {SystemAdminsCreateArgs} args - Arguments to create a SystemAdmins.
   * @example
   * // Create one SystemAdmins
   * const SystemAdmins = await prisma.systemAdmins.create({
   *   data: {
   *     // ... data to create a SystemAdmins
   *   }
   * })
   * 
   */
  create<T extends SystemAdminsCreateArgs>(args: Prisma.SelectSubset<T, SystemAdminsCreateArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SystemAdmins.
   * @param {SystemAdminsCreateManyArgs} args - Arguments to create many SystemAdmins.
   * @example
   * // Create many SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SystemAdminsCreateManyArgs>(args?: Prisma.SelectSubset<T, SystemAdminsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SystemAdmins and returns the data saved in the database.
   * @param {SystemAdminsCreateManyAndReturnArgs} args - Arguments to create many SystemAdmins.
   * @example
   * // Create many SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SystemAdmins and only return the `id`
   * const systemAdminsWithIdOnly = await prisma.systemAdmins.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SystemAdminsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SystemAdminsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SystemAdmins.
   * @param {SystemAdminsDeleteArgs} args - Arguments to delete one SystemAdmins.
   * @example
   * // Delete one SystemAdmins
   * const SystemAdmins = await prisma.systemAdmins.delete({
   *   where: {
   *     // ... filter to delete one SystemAdmins
   *   }
   * })
   * 
   */
  delete<T extends SystemAdminsDeleteArgs>(args: Prisma.SelectSubset<T, SystemAdminsDeleteArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SystemAdmins.
   * @param {SystemAdminsUpdateArgs} args - Arguments to update one SystemAdmins.
   * @example
   * // Update one SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SystemAdminsUpdateArgs>(args: Prisma.SelectSubset<T, SystemAdminsUpdateArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SystemAdmins.
   * @param {SystemAdminsDeleteManyArgs} args - Arguments to filter SystemAdmins to delete.
   * @example
   * // Delete a few SystemAdmins
   * const { count } = await prisma.systemAdmins.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SystemAdminsDeleteManyArgs>(args?: Prisma.SelectSubset<T, SystemAdminsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SystemAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SystemAdminsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SystemAdminsUpdateManyArgs>(args: Prisma.SelectSubset<T, SystemAdminsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SystemAdmins and returns the data updated in the database.
   * @param {SystemAdminsUpdateManyAndReturnArgs} args - Arguments to update many SystemAdmins.
   * @example
   * // Update many SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SystemAdmins and only return the `id`
   * const systemAdminsWithIdOnly = await prisma.systemAdmins.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SystemAdminsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SystemAdminsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SystemAdmins.
   * @param {SystemAdminsUpsertArgs} args - Arguments to update or create a SystemAdmins.
   * @example
   * // Update or create a SystemAdmins
   * const systemAdmins = await prisma.systemAdmins.upsert({
   *   create: {
   *     // ... data to create a SystemAdmins
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SystemAdmins we want to update
   *   }
   * })
   */
  upsert<T extends SystemAdminsUpsertArgs>(args: Prisma.SelectSubset<T, SystemAdminsUpsertArgs<ExtArgs>>): Prisma.Prisma__SystemAdminsClient<runtime.Types.Result.GetResult<Prisma.$SystemAdminsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SystemAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SystemAdminsCountArgs} args - Arguments to filter SystemAdmins to count.
   * @example
   * // Count the number of SystemAdmins
   * const count = await prisma.systemAdmins.count({
   *   where: {
   *     // ... the filter for the SystemAdmins we want to count
   *   }
   * })
  **/
  count<T extends SystemAdminsCountArgs>(
    args?: Prisma.Subset<T, SystemAdminsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SystemAdminsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SystemAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SystemAdminsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SystemAdminsAggregateArgs>(args: Prisma.Subset<T, SystemAdminsAggregateArgs>): Prisma.PrismaPromise<GetSystemAdminsAggregateType<T>>

  /**
   * Group by SystemAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SystemAdminsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SystemAdminsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SystemAdminsGroupByArgs['orderBy'] }
      : { orderBy?: SystemAdminsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SystemAdminsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSystemAdminsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SystemAdmins model
 */
readonly fields: SystemAdminsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SystemAdmins.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SystemAdminsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SystemAdmins model
 */
export interface SystemAdminsFieldRefs {
  readonly id: Prisma.FieldRef<"SystemAdmins", 'String'>
  readonly email: Prisma.FieldRef<"SystemAdmins", 'String'>
  readonly name: Prisma.FieldRef<"SystemAdmins", 'String'>
  readonly password_hash: Prisma.FieldRef<"SystemAdmins", 'String'>
  readonly created_at: Prisma.FieldRef<"SystemAdmins", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"SystemAdmins", 'DateTime'>
  readonly is_active: Prisma.FieldRef<"SystemAdmins", 'Boolean'>
}
    

// Custom InputTypes
/**
 * SystemAdmins findUnique
 */
export type SystemAdminsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * Filter, which SystemAdmins to fetch.
   */
  where: Prisma.SystemAdminsWhereUniqueInput
}

/**
 * SystemAdmins findUniqueOrThrow
 */
export type SystemAdminsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * Filter, which SystemAdmins to fetch.
   */
  where: Prisma.SystemAdminsWhereUniqueInput
}

/**
 * SystemAdmins findFirst
 */
export type SystemAdminsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * Filter, which SystemAdmins to fetch.
   */
  where?: Prisma.SystemAdminsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SystemAdmins to fetch.
   */
  orderBy?: Prisma.SystemAdminsOrderByWithRelationInput | Prisma.SystemAdminsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SystemAdmins.
   */
  cursor?: Prisma.SystemAdminsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SystemAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SystemAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SystemAdmins.
   */
  distinct?: Prisma.SystemAdminsScalarFieldEnum | Prisma.SystemAdminsScalarFieldEnum[]
}

/**
 * SystemAdmins findFirstOrThrow
 */
export type SystemAdminsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * Filter, which SystemAdmins to fetch.
   */
  where?: Prisma.SystemAdminsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SystemAdmins to fetch.
   */
  orderBy?: Prisma.SystemAdminsOrderByWithRelationInput | Prisma.SystemAdminsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SystemAdmins.
   */
  cursor?: Prisma.SystemAdminsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SystemAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SystemAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SystemAdmins.
   */
  distinct?: Prisma.SystemAdminsScalarFieldEnum | Prisma.SystemAdminsScalarFieldEnum[]
}

/**
 * SystemAdmins findMany
 */
export type SystemAdminsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * Filter, which SystemAdmins to fetch.
   */
  where?: Prisma.SystemAdminsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SystemAdmins to fetch.
   */
  orderBy?: Prisma.SystemAdminsOrderByWithRelationInput | Prisma.SystemAdminsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SystemAdmins.
   */
  cursor?: Prisma.SystemAdminsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SystemAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SystemAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SystemAdmins.
   */
  distinct?: Prisma.SystemAdminsScalarFieldEnum | Prisma.SystemAdminsScalarFieldEnum[]
}

/**
 * SystemAdmins create
 */
export type SystemAdminsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * The data needed to create a SystemAdmins.
   */
  data: Prisma.XOR<Prisma.SystemAdminsCreateInput, Prisma.SystemAdminsUncheckedCreateInput>
}

/**
 * SystemAdmins createMany
 */
export type SystemAdminsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SystemAdmins.
   */
  data: Prisma.SystemAdminsCreateManyInput | Prisma.SystemAdminsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SystemAdmins createManyAndReturn
 */
export type SystemAdminsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * The data used to create many SystemAdmins.
   */
  data: Prisma.SystemAdminsCreateManyInput | Prisma.SystemAdminsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SystemAdmins update
 */
export type SystemAdminsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * The data needed to update a SystemAdmins.
   */
  data: Prisma.XOR<Prisma.SystemAdminsUpdateInput, Prisma.SystemAdminsUncheckedUpdateInput>
  /**
   * Choose, which SystemAdmins to update.
   */
  where: Prisma.SystemAdminsWhereUniqueInput
}

/**
 * SystemAdmins updateMany
 */
export type SystemAdminsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SystemAdmins.
   */
  data: Prisma.XOR<Prisma.SystemAdminsUpdateManyMutationInput, Prisma.SystemAdminsUncheckedUpdateManyInput>
  /**
   * Filter which SystemAdmins to update
   */
  where?: Prisma.SystemAdminsWhereInput
  /**
   * Limit how many SystemAdmins to update.
   */
  limit?: number
}

/**
 * SystemAdmins updateManyAndReturn
 */
export type SystemAdminsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * The data used to update SystemAdmins.
   */
  data: Prisma.XOR<Prisma.SystemAdminsUpdateManyMutationInput, Prisma.SystemAdminsUncheckedUpdateManyInput>
  /**
   * Filter which SystemAdmins to update
   */
  where?: Prisma.SystemAdminsWhereInput
  /**
   * Limit how many SystemAdmins to update.
   */
  limit?: number
}

/**
 * SystemAdmins upsert
 */
export type SystemAdminsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * The filter to search for the SystemAdmins to update in case it exists.
   */
  where: Prisma.SystemAdminsWhereUniqueInput
  /**
   * In case the SystemAdmins found by the `where` argument doesn't exist, create a new SystemAdmins with this data.
   */
  create: Prisma.XOR<Prisma.SystemAdminsCreateInput, Prisma.SystemAdminsUncheckedCreateInput>
  /**
   * In case the SystemAdmins was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SystemAdminsUpdateInput, Prisma.SystemAdminsUncheckedUpdateInput>
}

/**
 * SystemAdmins delete
 */
export type SystemAdminsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
  /**
   * Filter which SystemAdmins to delete.
   */
  where: Prisma.SystemAdminsWhereUniqueInput
}

/**
 * SystemAdmins deleteMany
 */
export type SystemAdminsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SystemAdmins to delete
   */
  where?: Prisma.SystemAdminsWhereInput
  /**
   * Limit how many SystemAdmins to delete.
   */
  limit?: number
}

/**
 * SystemAdmins without action
 */
export type SystemAdminsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SystemAdmins
   */
  select?: Prisma.SystemAdminsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SystemAdmins
   */
  omit?: Prisma.SystemAdminsOmit<ExtArgs> | null
}
