
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tenants` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Tenants
 * 
 */
export type TenantsModel = runtime.Types.Result.DefaultSelection<Prisma.$TenantsPayload>

export type AggregateTenants = {
  _count: TenantsCountAggregateOutputType | null
  _avg: TenantsAvgAggregateOutputType | null
  _sum: TenantsSumAggregateOutputType | null
  _min: TenantsMinAggregateOutputType | null
  _max: TenantsMaxAggregateOutputType | null
}

export type TenantsAvgAggregateOutputType = {
  max_employees: number | null
  max_decisions: number | null
  max_storage_mb: number | null
  storage_used_mb: runtime.Decimal | null
}

export type TenantsSumAggregateOutputType = {
  max_employees: number | null
  max_decisions: number | null
  max_storage_mb: number | null
  storage_used_mb: runtime.Decimal | null
}

export type TenantsMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  status: $Enums.TenantStatus | null
  manager_id: string | null
  max_employees: number | null
  max_decisions: number | null
  max_storage_mb: number | null
  storage_used_mb: runtime.Decimal | null
  deleted_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type TenantsMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  status: $Enums.TenantStatus | null
  manager_id: string | null
  max_employees: number | null
  max_decisions: number | null
  max_storage_mb: number | null
  storage_used_mb: runtime.Decimal | null
  deleted_at: Date | null
  created_at: Date | null
  updated_at: Date | null
}

export type TenantsCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  status: number
  manager_id: number
  max_employees: number
  max_decisions: number
  max_storage_mb: number
  storage_used_mb: number
  deleted_at: number
  created_at: number
  updated_at: number
  _all: number
}


export type TenantsAvgAggregateInputType = {
  max_employees?: true
  max_decisions?: true
  max_storage_mb?: true
  storage_used_mb?: true
}

export type TenantsSumAggregateInputType = {
  max_employees?: true
  max_decisions?: true
  max_storage_mb?: true
  storage_used_mb?: true
}

export type TenantsMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  status?: true
  manager_id?: true
  max_employees?: true
  max_decisions?: true
  max_storage_mb?: true
  storage_used_mb?: true
  deleted_at?: true
  created_at?: true
  updated_at?: true
}

export type TenantsMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  status?: true
  manager_id?: true
  max_employees?: true
  max_decisions?: true
  max_storage_mb?: true
  storage_used_mb?: true
  deleted_at?: true
  created_at?: true
  updated_at?: true
}

export type TenantsCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  status?: true
  manager_id?: true
  max_employees?: true
  max_decisions?: true
  max_storage_mb?: true
  storage_used_mb?: true
  deleted_at?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type TenantsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tenants to aggregate.
   */
  where?: Prisma.TenantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantsOrderByWithRelationInput | Prisma.TenantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TenantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tenants
  **/
  _count?: true | TenantsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TenantsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TenantsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TenantsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TenantsMaxAggregateInputType
}

export type GetTenantsAggregateType<T extends TenantsAggregateArgs> = {
      [P in keyof T & keyof AggregateTenants]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTenants[P]>
    : Prisma.GetScalarType<T[P], AggregateTenants[P]>
}




export type TenantsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TenantsWhereInput
  orderBy?: Prisma.TenantsOrderByWithAggregationInput | Prisma.TenantsOrderByWithAggregationInput[]
  by: Prisma.TenantsScalarFieldEnum[] | Prisma.TenantsScalarFieldEnum
  having?: Prisma.TenantsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TenantsCountAggregateInputType | true
  _avg?: TenantsAvgAggregateInputType
  _sum?: TenantsSumAggregateInputType
  _min?: TenantsMinAggregateInputType
  _max?: TenantsMaxAggregateInputType
}

export type TenantsGroupByOutputType = {
  id: string
  name: string
  slug: string
  status: $Enums.TenantStatus
  manager_id: string | null
  max_employees: number | null
  max_decisions: number | null
  max_storage_mb: number | null
  storage_used_mb: runtime.Decimal | null
  deleted_at: Date | null
  created_at: Date
  updated_at: Date
  _count: TenantsCountAggregateOutputType | null
  _avg: TenantsAvgAggregateOutputType | null
  _sum: TenantsSumAggregateOutputType | null
  _min: TenantsMinAggregateOutputType | null
  _max: TenantsMaxAggregateOutputType | null
}

export type GetTenantsGroupByPayload<T extends TenantsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TenantsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TenantsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TenantsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TenantsGroupByOutputType[P]>
      }
    >
  >



export type TenantsWhereInput = {
  AND?: Prisma.TenantsWhereInput | Prisma.TenantsWhereInput[]
  OR?: Prisma.TenantsWhereInput[]
  NOT?: Prisma.TenantsWhereInput | Prisma.TenantsWhereInput[]
  id?: Prisma.StringFilter<"Tenants"> | string
  name?: Prisma.StringFilter<"Tenants"> | string
  slug?: Prisma.StringFilter<"Tenants"> | string
  status?: Prisma.EnumTenantStatusFilter<"Tenants"> | $Enums.TenantStatus
  manager_id?: Prisma.StringNullableFilter<"Tenants"> | string | null
  max_employees?: Prisma.IntNullableFilter<"Tenants"> | number | null
  max_decisions?: Prisma.IntNullableFilter<"Tenants"> | number | null
  max_storage_mb?: Prisma.IntNullableFilter<"Tenants"> | number | null
  storage_used_mb?: Prisma.DecimalNullableFilter<"Tenants"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"Tenants"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Tenants"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tenants"> | Date | string
  employees?: Prisma.EmployeesListRelationFilter
  manager?: Prisma.XOR<Prisma.EmployeesNullableScalarRelationFilter, Prisma.EmployeesWhereInput> | null
  inviteLinks?: Prisma.InviteLinksListRelationFilter
}

export type TenantsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
  manager_id?: Prisma.SortOrderInput | Prisma.SortOrder
  max_employees?: Prisma.SortOrderInput | Prisma.SortOrder
  max_decisions?: Prisma.SortOrderInput | Prisma.SortOrder
  max_storage_mb?: Prisma.SortOrderInput | Prisma.SortOrder
  storage_used_mb?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  employees?: Prisma.EmployeesOrderByRelationAggregateInput
  manager?: Prisma.EmployeesOrderByWithRelationInput
  inviteLinks?: Prisma.InviteLinksOrderByRelationAggregateInput
}

export type TenantsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.TenantsWhereInput | Prisma.TenantsWhereInput[]
  OR?: Prisma.TenantsWhereInput[]
  NOT?: Prisma.TenantsWhereInput | Prisma.TenantsWhereInput[]
  name?: Prisma.StringFilter<"Tenants"> | string
  status?: Prisma.EnumTenantStatusFilter<"Tenants"> | $Enums.TenantStatus
  manager_id?: Prisma.StringNullableFilter<"Tenants"> | string | null
  max_employees?: Prisma.IntNullableFilter<"Tenants"> | number | null
  max_decisions?: Prisma.IntNullableFilter<"Tenants"> | number | null
  max_storage_mb?: Prisma.IntNullableFilter<"Tenants"> | number | null
  storage_used_mb?: Prisma.DecimalNullableFilter<"Tenants"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"Tenants"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Tenants"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tenants"> | Date | string
  employees?: Prisma.EmployeesListRelationFilter
  manager?: Prisma.XOR<Prisma.EmployeesNullableScalarRelationFilter, Prisma.EmployeesWhereInput> | null
  inviteLinks?: Prisma.InviteLinksListRelationFilter
}, "id" | "slug">

export type TenantsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
  manager_id?: Prisma.SortOrderInput | Prisma.SortOrder
  max_employees?: Prisma.SortOrderInput | Prisma.SortOrder
  max_decisions?: Prisma.SortOrderInput | Prisma.SortOrder
  max_storage_mb?: Prisma.SortOrderInput | Prisma.SortOrder
  storage_used_mb?: Prisma.SortOrderInput | Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.TenantsCountOrderByAggregateInput
  _avg?: Prisma.TenantsAvgOrderByAggregateInput
  _max?: Prisma.TenantsMaxOrderByAggregateInput
  _min?: Prisma.TenantsMinOrderByAggregateInput
  _sum?: Prisma.TenantsSumOrderByAggregateInput
}

export type TenantsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TenantsScalarWhereWithAggregatesInput | Prisma.TenantsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TenantsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TenantsScalarWhereWithAggregatesInput | Prisma.TenantsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Tenants"> | string
  name?: Prisma.StringWithAggregatesFilter<"Tenants"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Tenants"> | string
  status?: Prisma.EnumTenantStatusWithAggregatesFilter<"Tenants"> | $Enums.TenantStatus
  manager_id?: Prisma.StringNullableWithAggregatesFilter<"Tenants"> | string | null
  max_employees?: Prisma.IntNullableWithAggregatesFilter<"Tenants"> | number | null
  max_decisions?: Prisma.IntNullableWithAggregatesFilter<"Tenants"> | number | null
  max_storage_mb?: Prisma.IntNullableWithAggregatesFilter<"Tenants"> | number | null
  storage_used_mb?: Prisma.DecimalNullableWithAggregatesFilter<"Tenants"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"Tenants"> | Date | string | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Tenants"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Tenants"> | Date | string
}

export type TenantsCreateInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  employees?: Prisma.EmployeesCreateNestedManyWithoutTenantInput
  manager?: Prisma.EmployeesCreateNestedOneWithoutTenantsInput
  inviteLinks?: Prisma.InviteLinksCreateNestedManyWithoutTenantInput
}

export type TenantsUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  manager_id?: string | null
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  employees?: Prisma.EmployeesUncheckedCreateNestedManyWithoutTenantInput
  inviteLinks?: Prisma.InviteLinksUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  employees?: Prisma.EmployeesUpdateManyWithoutTenantNestedInput
  manager?: Prisma.EmployeesUpdateOneWithoutTenantsNestedInput
  inviteLinks?: Prisma.InviteLinksUpdateManyWithoutTenantNestedInput
}

export type TenantsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  manager_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  employees?: Prisma.EmployeesUncheckedUpdateManyWithoutTenantNestedInput
  inviteLinks?: Prisma.InviteLinksUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantsCreateManyInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  manager_id?: string | null
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type TenantsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TenantsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  manager_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TenantsScalarRelationFilter = {
  is?: Prisma.TenantsWhereInput
  isNot?: Prisma.TenantsWhereInput
}

export type TenantsListRelationFilter = {
  every?: Prisma.TenantsWhereInput
  some?: Prisma.TenantsWhereInput
  none?: Prisma.TenantsWhereInput
}

export type TenantsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TenantsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
  max_employees?: Prisma.SortOrder
  max_decisions?: Prisma.SortOrder
  max_storage_mb?: Prisma.SortOrder
  storage_used_mb?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TenantsAvgOrderByAggregateInput = {
  max_employees?: Prisma.SortOrder
  max_decisions?: Prisma.SortOrder
  max_storage_mb?: Prisma.SortOrder
  storage_used_mb?: Prisma.SortOrder
}

export type TenantsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
  max_employees?: Prisma.SortOrder
  max_decisions?: Prisma.SortOrder
  max_storage_mb?: Prisma.SortOrder
  storage_used_mb?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TenantsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  status?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
  max_employees?: Prisma.SortOrder
  max_decisions?: Prisma.SortOrder
  max_storage_mb?: Prisma.SortOrder
  storage_used_mb?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TenantsSumOrderByAggregateInput = {
  max_employees?: Prisma.SortOrder
  max_decisions?: Prisma.SortOrder
  max_storage_mb?: Prisma.SortOrder
  storage_used_mb?: Prisma.SortOrder
}

export type TenantsCreateNestedOneWithoutEmployeesInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutEmployeesInput, Prisma.TenantsUncheckedCreateWithoutEmployeesInput>
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutEmployeesInput
  connect?: Prisma.TenantsWhereUniqueInput
}

export type TenantsCreateNestedManyWithoutManagerInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutManagerInput, Prisma.TenantsUncheckedCreateWithoutManagerInput> | Prisma.TenantsCreateWithoutManagerInput[] | Prisma.TenantsUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutManagerInput | Prisma.TenantsCreateOrConnectWithoutManagerInput[]
  createMany?: Prisma.TenantsCreateManyManagerInputEnvelope
  connect?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
}

export type TenantsUncheckedCreateNestedManyWithoutManagerInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutManagerInput, Prisma.TenantsUncheckedCreateWithoutManagerInput> | Prisma.TenantsCreateWithoutManagerInput[] | Prisma.TenantsUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutManagerInput | Prisma.TenantsCreateOrConnectWithoutManagerInput[]
  createMany?: Prisma.TenantsCreateManyManagerInputEnvelope
  connect?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
}

export type TenantsUpdateOneRequiredWithoutEmployeesNestedInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutEmployeesInput, Prisma.TenantsUncheckedCreateWithoutEmployeesInput>
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutEmployeesInput
  upsert?: Prisma.TenantsUpsertWithoutEmployeesInput
  connect?: Prisma.TenantsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantsUpdateToOneWithWhereWithoutEmployeesInput, Prisma.TenantsUpdateWithoutEmployeesInput>, Prisma.TenantsUncheckedUpdateWithoutEmployeesInput>
}

export type TenantsUpdateManyWithoutManagerNestedInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutManagerInput, Prisma.TenantsUncheckedCreateWithoutManagerInput> | Prisma.TenantsCreateWithoutManagerInput[] | Prisma.TenantsUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutManagerInput | Prisma.TenantsCreateOrConnectWithoutManagerInput[]
  upsert?: Prisma.TenantsUpsertWithWhereUniqueWithoutManagerInput | Prisma.TenantsUpsertWithWhereUniqueWithoutManagerInput[]
  createMany?: Prisma.TenantsCreateManyManagerInputEnvelope
  set?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  disconnect?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  delete?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  connect?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  update?: Prisma.TenantsUpdateWithWhereUniqueWithoutManagerInput | Prisma.TenantsUpdateWithWhereUniqueWithoutManagerInput[]
  updateMany?: Prisma.TenantsUpdateManyWithWhereWithoutManagerInput | Prisma.TenantsUpdateManyWithWhereWithoutManagerInput[]
  deleteMany?: Prisma.TenantsScalarWhereInput | Prisma.TenantsScalarWhereInput[]
}

export type TenantsUncheckedUpdateManyWithoutManagerNestedInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutManagerInput, Prisma.TenantsUncheckedCreateWithoutManagerInput> | Prisma.TenantsCreateWithoutManagerInput[] | Prisma.TenantsUncheckedCreateWithoutManagerInput[]
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutManagerInput | Prisma.TenantsCreateOrConnectWithoutManagerInput[]
  upsert?: Prisma.TenantsUpsertWithWhereUniqueWithoutManagerInput | Prisma.TenantsUpsertWithWhereUniqueWithoutManagerInput[]
  createMany?: Prisma.TenantsCreateManyManagerInputEnvelope
  set?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  disconnect?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  delete?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  connect?: Prisma.TenantsWhereUniqueInput | Prisma.TenantsWhereUniqueInput[]
  update?: Prisma.TenantsUpdateWithWhereUniqueWithoutManagerInput | Prisma.TenantsUpdateWithWhereUniqueWithoutManagerInput[]
  updateMany?: Prisma.TenantsUpdateManyWithWhereWithoutManagerInput | Prisma.TenantsUpdateManyWithWhereWithoutManagerInput[]
  deleteMany?: Prisma.TenantsScalarWhereInput | Prisma.TenantsScalarWhereInput[]
}

export type EnumTenantStatusFieldUpdateOperationsInput = {
  set?: $Enums.TenantStatus
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type TenantsCreateNestedOneWithoutInviteLinksInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutInviteLinksInput, Prisma.TenantsUncheckedCreateWithoutInviteLinksInput>
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutInviteLinksInput
  connect?: Prisma.TenantsWhereUniqueInput
}

export type TenantsUpdateOneRequiredWithoutInviteLinksNestedInput = {
  create?: Prisma.XOR<Prisma.TenantsCreateWithoutInviteLinksInput, Prisma.TenantsUncheckedCreateWithoutInviteLinksInput>
  connectOrCreate?: Prisma.TenantsCreateOrConnectWithoutInviteLinksInput
  upsert?: Prisma.TenantsUpsertWithoutInviteLinksInput
  connect?: Prisma.TenantsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantsUpdateToOneWithWhereWithoutInviteLinksInput, Prisma.TenantsUpdateWithoutInviteLinksInput>, Prisma.TenantsUncheckedUpdateWithoutInviteLinksInput>
}

export type TenantsCreateWithoutEmployeesInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  manager?: Prisma.EmployeesCreateNestedOneWithoutTenantsInput
  inviteLinks?: Prisma.InviteLinksCreateNestedManyWithoutTenantInput
}

export type TenantsUncheckedCreateWithoutEmployeesInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  manager_id?: string | null
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  inviteLinks?: Prisma.InviteLinksUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantsCreateOrConnectWithoutEmployeesInput = {
  where: Prisma.TenantsWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantsCreateWithoutEmployeesInput, Prisma.TenantsUncheckedCreateWithoutEmployeesInput>
}

export type TenantsCreateWithoutManagerInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  employees?: Prisma.EmployeesCreateNestedManyWithoutTenantInput
  inviteLinks?: Prisma.InviteLinksCreateNestedManyWithoutTenantInput
}

export type TenantsUncheckedCreateWithoutManagerInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  employees?: Prisma.EmployeesUncheckedCreateNestedManyWithoutTenantInput
  inviteLinks?: Prisma.InviteLinksUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantsCreateOrConnectWithoutManagerInput = {
  where: Prisma.TenantsWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantsCreateWithoutManagerInput, Prisma.TenantsUncheckedCreateWithoutManagerInput>
}

export type TenantsCreateManyManagerInputEnvelope = {
  data: Prisma.TenantsCreateManyManagerInput | Prisma.TenantsCreateManyManagerInput[]
  skipDuplicates?: boolean
}

export type TenantsUpsertWithoutEmployeesInput = {
  update: Prisma.XOR<Prisma.TenantsUpdateWithoutEmployeesInput, Prisma.TenantsUncheckedUpdateWithoutEmployeesInput>
  create: Prisma.XOR<Prisma.TenantsCreateWithoutEmployeesInput, Prisma.TenantsUncheckedCreateWithoutEmployeesInput>
  where?: Prisma.TenantsWhereInput
}

export type TenantsUpdateToOneWithWhereWithoutEmployeesInput = {
  where?: Prisma.TenantsWhereInput
  data: Prisma.XOR<Prisma.TenantsUpdateWithoutEmployeesInput, Prisma.TenantsUncheckedUpdateWithoutEmployeesInput>
}

export type TenantsUpdateWithoutEmployeesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  manager?: Prisma.EmployeesUpdateOneWithoutTenantsNestedInput
  inviteLinks?: Prisma.InviteLinksUpdateManyWithoutTenantNestedInput
}

export type TenantsUncheckedUpdateWithoutEmployeesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  manager_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  inviteLinks?: Prisma.InviteLinksUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantsUpsertWithWhereUniqueWithoutManagerInput = {
  where: Prisma.TenantsWhereUniqueInput
  update: Prisma.XOR<Prisma.TenantsUpdateWithoutManagerInput, Prisma.TenantsUncheckedUpdateWithoutManagerInput>
  create: Prisma.XOR<Prisma.TenantsCreateWithoutManagerInput, Prisma.TenantsUncheckedCreateWithoutManagerInput>
}

export type TenantsUpdateWithWhereUniqueWithoutManagerInput = {
  where: Prisma.TenantsWhereUniqueInput
  data: Prisma.XOR<Prisma.TenantsUpdateWithoutManagerInput, Prisma.TenantsUncheckedUpdateWithoutManagerInput>
}

export type TenantsUpdateManyWithWhereWithoutManagerInput = {
  where: Prisma.TenantsScalarWhereInput
  data: Prisma.XOR<Prisma.TenantsUpdateManyMutationInput, Prisma.TenantsUncheckedUpdateManyWithoutManagerInput>
}

export type TenantsScalarWhereInput = {
  AND?: Prisma.TenantsScalarWhereInput | Prisma.TenantsScalarWhereInput[]
  OR?: Prisma.TenantsScalarWhereInput[]
  NOT?: Prisma.TenantsScalarWhereInput | Prisma.TenantsScalarWhereInput[]
  id?: Prisma.StringFilter<"Tenants"> | string
  name?: Prisma.StringFilter<"Tenants"> | string
  slug?: Prisma.StringFilter<"Tenants"> | string
  status?: Prisma.EnumTenantStatusFilter<"Tenants"> | $Enums.TenantStatus
  manager_id?: Prisma.StringNullableFilter<"Tenants"> | string | null
  max_employees?: Prisma.IntNullableFilter<"Tenants"> | number | null
  max_decisions?: Prisma.IntNullableFilter<"Tenants"> | number | null
  max_storage_mb?: Prisma.IntNullableFilter<"Tenants"> | number | null
  storage_used_mb?: Prisma.DecimalNullableFilter<"Tenants"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.DateTimeNullableFilter<"Tenants"> | Date | string | null
  created_at?: Prisma.DateTimeFilter<"Tenants"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Tenants"> | Date | string
}

export type TenantsCreateWithoutInviteLinksInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  employees?: Prisma.EmployeesCreateNestedManyWithoutTenantInput
  manager?: Prisma.EmployeesCreateNestedOneWithoutTenantsInput
}

export type TenantsUncheckedCreateWithoutInviteLinksInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  manager_id?: string | null
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
  employees?: Prisma.EmployeesUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantsCreateOrConnectWithoutInviteLinksInput = {
  where: Prisma.TenantsWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantsCreateWithoutInviteLinksInput, Prisma.TenantsUncheckedCreateWithoutInviteLinksInput>
}

export type TenantsUpsertWithoutInviteLinksInput = {
  update: Prisma.XOR<Prisma.TenantsUpdateWithoutInviteLinksInput, Prisma.TenantsUncheckedUpdateWithoutInviteLinksInput>
  create: Prisma.XOR<Prisma.TenantsCreateWithoutInviteLinksInput, Prisma.TenantsUncheckedCreateWithoutInviteLinksInput>
  where?: Prisma.TenantsWhereInput
}

export type TenantsUpdateToOneWithWhereWithoutInviteLinksInput = {
  where?: Prisma.TenantsWhereInput
  data: Prisma.XOR<Prisma.TenantsUpdateWithoutInviteLinksInput, Prisma.TenantsUncheckedUpdateWithoutInviteLinksInput>
}

export type TenantsUpdateWithoutInviteLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  employees?: Prisma.EmployeesUpdateManyWithoutTenantNestedInput
  manager?: Prisma.EmployeesUpdateOneWithoutTenantsNestedInput
}

export type TenantsUncheckedUpdateWithoutInviteLinksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  manager_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  employees?: Prisma.EmployeesUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantsCreateManyManagerInput = {
  id?: string
  name: string
  slug: string
  status?: $Enums.TenantStatus
  max_employees?: number | null
  max_decisions?: number | null
  max_storage_mb?: number | null
  storage_used_mb?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Date | string | null
  created_at?: Date | string
  updated_at?: Date | string
}

export type TenantsUpdateWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  employees?: Prisma.EmployeesUpdateManyWithoutTenantNestedInput
  inviteLinks?: Prisma.InviteLinksUpdateManyWithoutTenantNestedInput
}

export type TenantsUncheckedUpdateWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  employees?: Prisma.EmployeesUncheckedUpdateManyWithoutTenantNestedInput
  inviteLinks?: Prisma.InviteLinksUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantsUncheckedUpdateManyWithoutManagerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumTenantStatusFieldUpdateOperationsInput | $Enums.TenantStatus
  max_employees?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_decisions?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  max_storage_mb?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_used_mb?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TenantsCountOutputType
 */

export type TenantsCountOutputType = {
  employees: number
  inviteLinks: number
}

export type TenantsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employees?: boolean | TenantsCountOutputTypeCountEmployeesArgs
  inviteLinks?: boolean | TenantsCountOutputTypeCountInviteLinksArgs
}

/**
 * TenantsCountOutputType without action
 */
export type TenantsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TenantsCountOutputType
   */
  select?: Prisma.TenantsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TenantsCountOutputType without action
 */
export type TenantsCountOutputTypeCountEmployeesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmployeesWhereInput
}

/**
 * TenantsCountOutputType without action
 */
export type TenantsCountOutputTypeCountInviteLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InviteLinksWhereInput
}


export type TenantsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
  manager_id?: boolean
  max_employees?: boolean
  max_decisions?: boolean
  max_storage_mb?: boolean
  storage_used_mb?: boolean
  deleted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  employees?: boolean | Prisma.Tenants$employeesArgs<ExtArgs>
  manager?: boolean | Prisma.Tenants$managerArgs<ExtArgs>
  inviteLinks?: boolean | Prisma.Tenants$inviteLinksArgs<ExtArgs>
  _count?: boolean | Prisma.TenantsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tenants"]>

export type TenantsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
  manager_id?: boolean
  max_employees?: boolean
  max_decisions?: boolean
  max_storage_mb?: boolean
  storage_used_mb?: boolean
  deleted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  manager?: boolean | Prisma.Tenants$managerArgs<ExtArgs>
}, ExtArgs["result"]["tenants"]>

export type TenantsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
  manager_id?: boolean
  max_employees?: boolean
  max_decisions?: boolean
  max_storage_mb?: boolean
  storage_used_mb?: boolean
  deleted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
  manager?: boolean | Prisma.Tenants$managerArgs<ExtArgs>
}, ExtArgs["result"]["tenants"]>

export type TenantsSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  status?: boolean
  manager_id?: boolean
  max_employees?: boolean
  max_decisions?: boolean
  max_storage_mb?: boolean
  storage_used_mb?: boolean
  deleted_at?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type TenantsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "status" | "manager_id" | "max_employees" | "max_decisions" | "max_storage_mb" | "storage_used_mb" | "deleted_at" | "created_at" | "updated_at", ExtArgs["result"]["tenants"]>
export type TenantsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employees?: boolean | Prisma.Tenants$employeesArgs<ExtArgs>
  manager?: boolean | Prisma.Tenants$managerArgs<ExtArgs>
  inviteLinks?: boolean | Prisma.Tenants$inviteLinksArgs<ExtArgs>
  _count?: boolean | Prisma.TenantsCountOutputTypeDefaultArgs<ExtArgs>
}
export type TenantsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  manager?: boolean | Prisma.Tenants$managerArgs<ExtArgs>
}
export type TenantsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  manager?: boolean | Prisma.Tenants$managerArgs<ExtArgs>
}

export type $TenantsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tenants"
  objects: {
    employees: Prisma.$EmployeesPayload<ExtArgs>[]
    manager: Prisma.$EmployeesPayload<ExtArgs> | null
    inviteLinks: Prisma.$InviteLinksPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    status: $Enums.TenantStatus
    manager_id: string | null
    max_employees: number | null
    max_decisions: number | null
    max_storage_mb: number | null
    storage_used_mb: runtime.Decimal | null
    deleted_at: Date | null
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["tenants"]>
  composites: {}
}

export type TenantsGetPayload<S extends boolean | null | undefined | TenantsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TenantsPayload, S>

export type TenantsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TenantsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TenantsCountAggregateInputType | true
  }

export interface TenantsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tenants'], meta: { name: 'Tenants' } }
  /**
   * Find zero or one Tenants that matches the filter.
   * @param {TenantsFindUniqueArgs} args - Arguments to find a Tenants
   * @example
   * // Get one Tenants
   * const tenants = await prisma.tenants.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TenantsFindUniqueArgs>(args: Prisma.SelectSubset<T, TenantsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tenants that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TenantsFindUniqueOrThrowArgs} args - Arguments to find a Tenants
   * @example
   * // Get one Tenants
   * const tenants = await prisma.tenants.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TenantsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TenantsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tenants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantsFindFirstArgs} args - Arguments to find a Tenants
   * @example
   * // Get one Tenants
   * const tenants = await prisma.tenants.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TenantsFindFirstArgs>(args?: Prisma.SelectSubset<T, TenantsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tenants that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantsFindFirstOrThrowArgs} args - Arguments to find a Tenants
   * @example
   * // Get one Tenants
   * const tenants = await prisma.tenants.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TenantsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TenantsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tenants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tenants
   * const tenants = await prisma.tenants.findMany()
   * 
   * // Get first 10 Tenants
   * const tenants = await prisma.tenants.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tenantsWithIdOnly = await prisma.tenants.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TenantsFindManyArgs>(args?: Prisma.SelectSubset<T, TenantsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tenants.
   * @param {TenantsCreateArgs} args - Arguments to create a Tenants.
   * @example
   * // Create one Tenants
   * const Tenants = await prisma.tenants.create({
   *   data: {
   *     // ... data to create a Tenants
   *   }
   * })
   * 
   */
  create<T extends TenantsCreateArgs>(args: Prisma.SelectSubset<T, TenantsCreateArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tenants.
   * @param {TenantsCreateManyArgs} args - Arguments to create many Tenants.
   * @example
   * // Create many Tenants
   * const tenants = await prisma.tenants.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TenantsCreateManyArgs>(args?: Prisma.SelectSubset<T, TenantsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tenants and returns the data saved in the database.
   * @param {TenantsCreateManyAndReturnArgs} args - Arguments to create many Tenants.
   * @example
   * // Create many Tenants
   * const tenants = await prisma.tenants.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tenants and only return the `id`
   * const tenantsWithIdOnly = await prisma.tenants.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TenantsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TenantsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tenants.
   * @param {TenantsDeleteArgs} args - Arguments to delete one Tenants.
   * @example
   * // Delete one Tenants
   * const Tenants = await prisma.tenants.delete({
   *   where: {
   *     // ... filter to delete one Tenants
   *   }
   * })
   * 
   */
  delete<T extends TenantsDeleteArgs>(args: Prisma.SelectSubset<T, TenantsDeleteArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tenants.
   * @param {TenantsUpdateArgs} args - Arguments to update one Tenants.
   * @example
   * // Update one Tenants
   * const tenants = await prisma.tenants.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TenantsUpdateArgs>(args: Prisma.SelectSubset<T, TenantsUpdateArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tenants.
   * @param {TenantsDeleteManyArgs} args - Arguments to filter Tenants to delete.
   * @example
   * // Delete a few Tenants
   * const { count } = await prisma.tenants.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TenantsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TenantsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tenants
   * const tenants = await prisma.tenants.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TenantsUpdateManyArgs>(args: Prisma.SelectSubset<T, TenantsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tenants and returns the data updated in the database.
   * @param {TenantsUpdateManyAndReturnArgs} args - Arguments to update many Tenants.
   * @example
   * // Update many Tenants
   * const tenants = await prisma.tenants.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tenants and only return the `id`
   * const tenantsWithIdOnly = await prisma.tenants.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TenantsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TenantsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tenants.
   * @param {TenantsUpsertArgs} args - Arguments to update or create a Tenants.
   * @example
   * // Update or create a Tenants
   * const tenants = await prisma.tenants.upsert({
   *   create: {
   *     // ... data to create a Tenants
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tenants we want to update
   *   }
   * })
   */
  upsert<T extends TenantsUpsertArgs>(args: Prisma.SelectSubset<T, TenantsUpsertArgs<ExtArgs>>): Prisma.Prisma__TenantsClient<runtime.Types.Result.GetResult<Prisma.$TenantsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantsCountArgs} args - Arguments to filter Tenants to count.
   * @example
   * // Count the number of Tenants
   * const count = await prisma.tenants.count({
   *   where: {
   *     // ... the filter for the Tenants we want to count
   *   }
   * })
  **/
  count<T extends TenantsCountArgs>(
    args?: Prisma.Subset<T, TenantsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TenantsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TenantsAggregateArgs>(args: Prisma.Subset<T, TenantsAggregateArgs>): Prisma.PrismaPromise<GetTenantsAggregateType<T>>

  /**
   * Group by Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TenantsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TenantsGroupByArgs['orderBy'] }
      : { orderBy?: TenantsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TenantsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTenantsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tenants model
 */
readonly fields: TenantsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tenants.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TenantsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  employees<T extends Prisma.Tenants$employeesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenants$employeesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  manager<T extends Prisma.Tenants$managerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenants$managerArgs<ExtArgs>>): Prisma.Prisma__EmployeesClient<runtime.Types.Result.GetResult<Prisma.$EmployeesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  inviteLinks<T extends Prisma.Tenants$inviteLinksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenants$inviteLinksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InviteLinksPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tenants model
 */
export interface TenantsFieldRefs {
  readonly id: Prisma.FieldRef<"Tenants", 'String'>
  readonly name: Prisma.FieldRef<"Tenants", 'String'>
  readonly slug: Prisma.FieldRef<"Tenants", 'String'>
  readonly status: Prisma.FieldRef<"Tenants", 'TenantStatus'>
  readonly manager_id: Prisma.FieldRef<"Tenants", 'String'>
  readonly max_employees: Prisma.FieldRef<"Tenants", 'Int'>
  readonly max_decisions: Prisma.FieldRef<"Tenants", 'Int'>
  readonly max_storage_mb: Prisma.FieldRef<"Tenants", 'Int'>
  readonly storage_used_mb: Prisma.FieldRef<"Tenants", 'Decimal'>
  readonly deleted_at: Prisma.FieldRef<"Tenants", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"Tenants", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Tenants", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Tenants findUnique
 */
export type TenantsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * Filter, which Tenants to fetch.
   */
  where: Prisma.TenantsWhereUniqueInput
}

/**
 * Tenants findUniqueOrThrow
 */
export type TenantsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * Filter, which Tenants to fetch.
   */
  where: Prisma.TenantsWhereUniqueInput
}

/**
 * Tenants findFirst
 */
export type TenantsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * Filter, which Tenants to fetch.
   */
  where?: Prisma.TenantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantsOrderByWithRelationInput | Prisma.TenantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tenants.
   */
  cursor?: Prisma.TenantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantsScalarFieldEnum | Prisma.TenantsScalarFieldEnum[]
}

/**
 * Tenants findFirstOrThrow
 */
export type TenantsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * Filter, which Tenants to fetch.
   */
  where?: Prisma.TenantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantsOrderByWithRelationInput | Prisma.TenantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tenants.
   */
  cursor?: Prisma.TenantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantsScalarFieldEnum | Prisma.TenantsScalarFieldEnum[]
}

/**
 * Tenants findMany
 */
export type TenantsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * Filter, which Tenants to fetch.
   */
  where?: Prisma.TenantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantsOrderByWithRelationInput | Prisma.TenantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tenants.
   */
  cursor?: Prisma.TenantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantsScalarFieldEnum | Prisma.TenantsScalarFieldEnum[]
}

/**
 * Tenants create
 */
export type TenantsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * The data needed to create a Tenants.
   */
  data: Prisma.XOR<Prisma.TenantsCreateInput, Prisma.TenantsUncheckedCreateInput>
}

/**
 * Tenants createMany
 */
export type TenantsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tenants.
   */
  data: Prisma.TenantsCreateManyInput | Prisma.TenantsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tenants createManyAndReturn
 */
export type TenantsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * The data used to create many Tenants.
   */
  data: Prisma.TenantsCreateManyInput | Prisma.TenantsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Tenants update
 */
export type TenantsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * The data needed to update a Tenants.
   */
  data: Prisma.XOR<Prisma.TenantsUpdateInput, Prisma.TenantsUncheckedUpdateInput>
  /**
   * Choose, which Tenants to update.
   */
  where: Prisma.TenantsWhereUniqueInput
}

/**
 * Tenants updateMany
 */
export type TenantsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tenants.
   */
  data: Prisma.XOR<Prisma.TenantsUpdateManyMutationInput, Prisma.TenantsUncheckedUpdateManyInput>
  /**
   * Filter which Tenants to update
   */
  where?: Prisma.TenantsWhereInput
  /**
   * Limit how many Tenants to update.
   */
  limit?: number
}

/**
 * Tenants updateManyAndReturn
 */
export type TenantsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * The data used to update Tenants.
   */
  data: Prisma.XOR<Prisma.TenantsUpdateManyMutationInput, Prisma.TenantsUncheckedUpdateManyInput>
  /**
   * Filter which Tenants to update
   */
  where?: Prisma.TenantsWhereInput
  /**
   * Limit how many Tenants to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Tenants upsert
 */
export type TenantsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * The filter to search for the Tenants to update in case it exists.
   */
  where: Prisma.TenantsWhereUniqueInput
  /**
   * In case the Tenants found by the `where` argument doesn't exist, create a new Tenants with this data.
   */
  create: Prisma.XOR<Prisma.TenantsCreateInput, Prisma.TenantsUncheckedCreateInput>
  /**
   * In case the Tenants was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TenantsUpdateInput, Prisma.TenantsUncheckedUpdateInput>
}

/**
 * Tenants delete
 */
export type TenantsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
  /**
   * Filter which Tenants to delete.
   */
  where: Prisma.TenantsWhereUniqueInput
}

/**
 * Tenants deleteMany
 */
export type TenantsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tenants to delete
   */
  where?: Prisma.TenantsWhereInput
  /**
   * Limit how many Tenants to delete.
   */
  limit?: number
}

/**
 * Tenants.employees
 */
export type Tenants$employeesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  where?: Prisma.EmployeesWhereInput
  orderBy?: Prisma.EmployeesOrderByWithRelationInput | Prisma.EmployeesOrderByWithRelationInput[]
  cursor?: Prisma.EmployeesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmployeesScalarFieldEnum | Prisma.EmployeesScalarFieldEnum[]
}

/**
 * Tenants.manager
 */
export type Tenants$managerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Employees
   */
  select?: Prisma.EmployeesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Employees
   */
  omit?: Prisma.EmployeesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmployeesInclude<ExtArgs> | null
  where?: Prisma.EmployeesWhereInput
}

/**
 * Tenants.inviteLinks
 */
export type Tenants$inviteLinksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InviteLinks
   */
  select?: Prisma.InviteLinksSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InviteLinks
   */
  omit?: Prisma.InviteLinksOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InviteLinksInclude<ExtArgs> | null
  where?: Prisma.InviteLinksWhereInput
  orderBy?: Prisma.InviteLinksOrderByWithRelationInput | Prisma.InviteLinksOrderByWithRelationInput[]
  cursor?: Prisma.InviteLinksWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InviteLinksScalarFieldEnum | Prisma.InviteLinksScalarFieldEnum[]
}

/**
 * Tenants without action
 */
export type TenantsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenants
   */
  select?: Prisma.TenantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenants
   */
  omit?: Prisma.TenantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantsInclude<ExtArgs> | null
}
